export const LESSONS = [
  {
    id: 'intro',
    title: 'Introduction to Electrolysis',
    icon: '⚡',
    time: '20 min',
    topic: 'Introduction to Electrolysis',
    content: [
      { type: 'heading', text: 'What is Electrolysis?' },
      { type: 'text', text: 'Electrolysis is the process of using electrical energy to drive a non-spontaneous chemical reaction — specifically, the decomposition of an ionic compound (the electrolyte) into its constituent elements.' },
      { type: 'keyPoints', items: [
        'Electrolyte: an ionic compound that conducts electricity when molten or dissolved in water',
        'Non-electrolytes: covalent compounds that cannot conduct electricity (e.g. sugar, ethanol)',
        'The electrical energy breaks ionic bonds and causes ions to discharge at electrodes',
      ]},
      { type: 'heading', text: 'Conductors of Electricity' },
      { type: 'table', headers: ['Type', 'Examples', 'Charge Carriers'],
        rows: [
          ['Metallic conductors', 'Cu, Fe, graphite', 'Delocalised electrons'],
          ['Electrolytic conductors', 'NaCl(aq), CuSO₄(aq), molten KBr', 'Mobile ions'],
          ['Non-conductors', 'Sugar solution, distilled water, solid NaCl', 'None'],
        ]
      },
      { type: 'heading', text: 'The Electrolytic Cell' },
      { type: 'text', text: 'An electrolytic cell consists of: a DC power supply (battery), two electrodes submerged in the electrolyte, and the electrolyte itself.' },
      { type: 'keyPoints', items: [
        'Anode (+): the positive electrode connected to the positive terminal of the battery. Oxidation occurs here.',
        'Cathode (−): the negative electrode connected to the negative terminal. Reduction occurs here.',
        'Anions (negatively charged ions) migrate toward the anode.',
        'Cations (positively charged ions) migrate toward the cathode.',
      ]},
      { type: 'equation', label: 'Memory aid', text: 'AN OX — RED CAT: ANode = OXidation, REDuction = CAThode' },
      { type: 'heading', text: 'Electron Flow' },
      { type: 'text', text: 'Electrons are produced at the anode (when anions are oxidised) and travel through the external circuit (wires) to the cathode, where they reduce the cations. Inside the electrolyte, charge is carried by the movement of ions, not electrons.' },
      { type: 'equation', label: 'Conventional current', text: 'Current flows: + terminal → anode → electrolyte (ions) → cathode → − terminal' },
      { type: 'equation', label: 'Electron flow', text: 'Electrons flow: − terminal → cathode ← [external wire] ← anode ← + terminal' },
      { type: 'warn', text: 'Common mistake: students often say electrons flow through the electrolyte. They do NOT — only ions move inside the solution.' },
      { type: 'heading', text: 'Electrolysis vs Voltaic Cells' },
      { type: 'table', headers: ['Feature', 'Electrolytic Cell', 'Voltaic Cell'],
        rows: [
          ['Energy conversion', 'Electrical → Chemical', 'Chemical → Electrical'],
          ['External power', 'Required (battery)', 'Not needed'],
          ['Anode charge', 'Positive (+)', 'Negative (−)'],
          ['Cathode charge', 'Negative (−)', 'Positive (+)'],
          ['Spontaneity', 'Non-spontaneous', 'Spontaneous'],
        ]
      },
    ],
    quiz: [
      { id: 'q1', type: 'mcq', question: 'Which of the following can conduct electricity in the solid state?',
        options: { A: 'Sodium chloride (NaCl)', B: 'Copper wire', C: 'Sugar (C₁₂H₂₂O₁₁)', D: 'Distilled water' },
        answer: 'B', explanation: 'Metallic conductors like copper have delocalised electrons that carry charge. Solid NaCl has no mobile ions. Sugar and distilled water have no charge carriers.' },
      { id: 'q2', type: 'mcq', question: 'During electrolysis, which process occurs at the cathode?',
        options: { A: 'Oxidation of anions', B: 'Reduction of cations', C: 'Oxidation of cations', D: 'Reduction of anions' },
        answer: 'B', explanation: 'The cathode is negative, attracting cations. Electrons are supplied to the cathode by the external circuit, so cations gain electrons — i.e., are reduced. RED CAT = REDuction at CAThode.' },
      { id: 'q3', type: 'mcq', question: 'An aqueous solution of copper(II) sulfate does NOT conduct electricity when:',
        options: { A: 'It is diluted with water', B: 'The copper sulfate is not dissolved', C: 'The temperature is raised', D: 'More copper sulfate is dissolved' },
        answer: 'B', explanation: 'Conductivity requires mobile ions. Only when the ionic compound is dissolved (or molten) can its ions move. Solid copper sulfate has no mobile ions and will not conduct.' },
      { id: 'q4', type: 'structured', question: 'Explain, with reference to charge carriers, why solid sodium chloride does not conduct electricity but molten sodium chloride does.',
        hints: ['Think about where the ions are in each state.', 'What allows charge carriers to move?'],
        answer: 'In solid NaCl, Na⁺ and Cl⁻ ions are held in a fixed lattice and cannot move, so there are no mobile charge carriers and it does not conduct. In molten NaCl, the lattice structure breaks down, allowing Na⁺ and Cl⁻ ions to move freely and carry charge, so it conducts electricity. (2 marks: 1 for solid state explanation, 1 for molten state explanation)' },
      { id: 'q5', type: 'mcq', question: 'Electrons in the external circuit of an electrolytic cell flow from:',
        options: { A: 'Cathode to anode', B: 'Positive terminal of battery to anode', C: 'Anode to cathode through the electrolyte', D: 'Anode to cathode through the external wire' },
        answer: 'D', explanation: 'Electrons are produced by oxidation reactions at the anode and flow through the external wire to the cathode, where they participate in reduction reactions. Electrons cannot flow through the electrolyte — only ions move there.' },
    ]
  },

  {
    id: 'molten',
    title: 'Electrolysis of Molten Salts',
    icon: '🔥',
    time: '25 min',
    topic: 'Electrolysis of Molten Salts',
    content: [
      { type: 'heading', text: 'Why Molten Salts?' },
      { type: 'text', text: 'When an ionic solid is melted, the ions become mobile. This is the simplest case of electrolysis because there are only two types of ions present — no water molecules to complicate matters.' },
      { type: 'heading', text: 'Electrolysis of Molten Lead(II) Bromide (PbBr₂)' },
      { type: 'text', text: 'Molten PbBr₂ contains Pb²⁺ and Br⁻ ions. On electrolysis:' },
      { type: 'keyPoints', items: [
        'Pb²⁺ ions (cations) migrate to the cathode',
        'Br⁻ ions (anions) migrate to the anode',
        'At the cathode: Pb²⁺ is reduced to grey liquid lead metal',
        'At the anode: Br⁻ is oxidised to brown/orange bromine vapour',
      ]},
      { type: 'equation', label: 'Cathode (reduction):', text: 'Pb²⁺(l) + 2e⁻ → Pb(l)' },
      { type: 'equation', label: 'Anode (oxidation):', text: '2Br⁻(l) → Br₂(g) + 2e⁻' },
      { type: 'equation', label: 'Overall:', text: 'PbBr₂(l) → Pb(l) + Br₂(g)' },
      { type: 'info', text: 'Observation: Grey liquid metal appears at the cathode. Brown/orange fumes appear at the anode. The electrolyte becomes colourless as Br⁻ is consumed.' },
      { type: 'heading', text: 'Electrolysis of Molten Sodium Chloride (NaCl)' },
      { type: 'equation', label: 'Cathode:', text: 'Na⁺(l) + e⁻ → Na(l)' },
      { type: 'equation', label: 'Anode:', text: '2Cl⁻(l) → Cl₂(g) + 2e⁻' },
      { type: 'text', text: 'Sodium metal (highly reactive, burns in air/water) is produced at the cathode. Chlorine gas (yellowish-green, pungent) is produced at the anode. This is the industrial basis for sodium and chlorine production.' },
      { type: 'heading', text: 'General Pattern for Molten Salts' },
      { type: 'table', headers: ['Electrolyte', 'Cathode product', 'Anode product'],
        rows: [
          ['Molten PbBr₂', 'Lead (grey metal)', 'Bromine (brown gas)'],
          ['Molten NaCl', 'Sodium (silver metal)', 'Chlorine (yellow-green gas)'],
          ['Molten MgCl₂', 'Magnesium (grey metal)', 'Chlorine (yellow-green gas)'],
          ['Molten Al₂O₃', 'Aluminium (silver metal)', 'Oxygen (colourless gas)'],
          ['Molten KI', 'Potassium (silver metal)', 'Iodine (purple vapour)'],
        ]
      },
      { type: 'warn', text: 'The metal produced at the cathode is always the metal in the ionic compound. The non-metal produced at the anode comes from the anion (Cl⁻ → Cl₂, Br⁻ → Br₂, O²⁻ → O₂, I⁻ → I₂).' },
      { type: 'heading', text: 'Why High Temperature is Needed' },
      { type: 'text', text: 'The ionic solid must be fully melted so that ions have enough thermal energy to move freely through the melt. Below the melting point, electrolysis cannot occur because the ions are locked in the crystal lattice.' },
    ],
    quiz: [
      { id: 'q1', type: 'mcq', question: 'Molten lead(II) bromide is electrolysed using carbon electrodes. Which observation would be made at the anode?',
        options: { A: 'Grey solid deposits', B: 'Colourless gas is produced', C: 'Brown fumes are produced', D: 'The electrode dissolves' },
        answer: 'C', explanation: 'At the anode, Br⁻ ions are oxidised to Br₂: 2Br⁻ → Br₂ + 2e⁻. Bromine is a brown/orange gas at the temperature of the experiment.' },
      { id: 'q2', type: 'mcq', question: 'In the electrolysis of molten NaCl, what is produced at the cathode?',
        options: { A: 'Chlorine gas', B: 'Sodium metal', C: 'Hydrogen gas', D: 'Oxygen gas' },
        answer: 'B', explanation: 'Na⁺ is the only cation present in molten NaCl. At the cathode: Na⁺ + e⁻ → Na. No water is present, so no H₂ can form.' },
      { id: 'q3', type: 'structured', question: 'Write the ionic half-equations for the electrode reactions when molten magnesium chloride (MgCl₂) is electrolysed.',
        hints: ['MgCl₂ contains Mg²⁺ and Cl⁻ ions.', 'Remember which ion goes to which electrode.'],
        answer: 'Cathode: Mg²⁺(l) + 2e⁻ → Mg(l) [1 mark]\nAnode: 2Cl⁻(l) → Cl₂(g) + 2e⁻ [1 mark]' },
      { id: 'q4', type: 'mcq', question: 'Why is solid NaCl not used in place of molten NaCl for electrolysis?',
        options: { A: 'Solid NaCl has no ions', B: 'Ions in solid NaCl are not mobile', C: 'Solid NaCl decomposes when heated', D: 'The melting point of NaCl is too low' },
        answer: 'B', explanation: 'Solid NaCl contains Na⁺ and Cl⁻ ions but they are fixed in the crystal lattice. Electrolysis requires mobile charge carriers (ions), which only exist once the solid is melted.' },
      { id: 'q5', type: 'mcq', question: 'What is the role of the electrons transferred in the external circuit during electrolysis?',
        options: { A: 'They carry charge through the electrolyte', B: 'They convert cations to anions at the cathode', C: 'They allow reduction of cations at the cathode and oxidation at the anode', D: 'They heat the electrolyte' },
        answer: 'C', explanation: 'Electrons flow from the battery through the anode into the circuit, enabling oxidation at the anode (anions lose electrons). At the cathode, electrons arrive from the external circuit and are given to cations (reduction).' },
    ]
  },

  {
    id: 'aqueous',
    title: 'Electrolysis of Aqueous Solutions',
    icon: '💧',
    time: '35 min',
    topic: 'Electrolysis of Aqueous Solutions',
    content: [
      { type: 'heading', text: 'The Complication: Water' },
      { type: 'text', text: 'Aqueous solutions contain both the dissolved ions AND water molecules. Water itself can be oxidised at the anode or reduced at the cathode, so the products are not always predictable. We apply the preferential discharge theory.' },
      { type: 'equation', label: 'Water self-ionises (slightly):', text: '2H₂O ⇌ H₃O⁺ + OH⁻  (or H₂O ⇌ H⁺ + OH⁻)' },
      { type: 'heading', text: 'Electrochemical Series — Ion Discharge Order' },
      { type: 'text', text: 'Ions compete to be discharged. The ion that is discharged preferentially depends on its position in the electrochemical series (reduction potential).' },
      { type: 'table', headers: ['Cathode — Cations (ease of reduction ↓)', 'Tendency'],
        rows: [
          ['K⁺, Na⁺, Ca²⁺, Mg²⁺, Al³⁺', 'Very hard to reduce (water reduced instead)'],
          ['Zn²⁺, Fe²⁺, Ni²⁺', 'Moderate'],
          ['Pb²⁺, H⁺', 'Moderately easy'],
          ['Cu²⁺, Ag⁺, Au³⁺', 'Easy to reduce — deposited preferentially'],
        ]
      },
      { type: 'table', headers: ['Anode — Anions (ease of oxidation ↓)', 'Tendency'],
        rows: [
          ['SO₄²⁻, NO₃⁻, OH⁻ from water', 'Hard to oxidise (water oxidised instead at lower conc.)'],
          ['OH⁻ ions', 'Easier when concentrated'],
          ['Cl⁻, Br⁻, I⁻', 'Easily oxidised — discharged preferentially when concentrated'],
        ]
      },
      { type: 'heading', text: 'Key Rules for Aqueous Electrolysis' },
      { type: 'keyPoints', items: [
        'Cathode: If Cu²⁺, Ag⁺, Pb²⁺ present → metal deposits. If only reactive metal ions (Na⁺, K⁺, etc.) → H₂ gas from water.',
        'Anode: If Cl⁻, Br⁻, I⁻ are concentrated → halogen gas discharged. Otherwise → O₂ from water oxidation.',
        'Concentration matters: dilute Cl⁻ → O₂ produced; concentrated Cl⁻ → Cl₂ produced.',
      ]},
      { type: 'heading', text: 'Example 1: Electrolysis of CuSO₄(aq) with Inert Electrodes' },
      { type: 'text', text: 'Ions present: Cu²⁺, SO₄²⁻, H⁺, OH⁻ (from water).' },
      { type: 'equation', label: 'Cathode:', text: 'Cu²⁺(aq) + 2e⁻ → Cu(s)   [Cu²⁺ discharged in preference to H⁺]' },
      { type: 'equation', label: 'Anode:', text: '2H₂O(l) → O₂(g) + 4H⁺(aq) + 4e⁻   [SO₄²⁻ not discharged; water oxidised]' },
      { type: 'info', text: 'Observations: Reddish-brown copper deposits at cathode. Colourless oxygen bubbles at anode. Blue colour of solution fades (Cu²⁺ depleted). Solution becomes acidic (H⁺ produced).' },
      { type: 'heading', text: 'Example 2: Electrolysis of Dilute H₂SO₄(aq)' },
      { type: 'equation', label: 'Cathode:', text: '2H⁺(aq) + 2e⁻ → H₂(g)' },
      { type: 'equation', label: 'Anode:', text: '2H₂O(l) → O₂(g) + 4H⁺(aq) + 4e⁻' },
      { type: 'info', text: 'Volume ratio: H₂ : O₂ = 2 : 1 (by moles, both gases, so 2:1 by volume at same T,P). H₂SO₄ concentration increases as water is consumed.' },
      { type: 'heading', text: 'Example 3: Electrolysis of Brine (Concentrated NaCl(aq))' },
      { type: 'equation', label: 'Cathode:', text: '2H₂O(l) + 2e⁻ → H₂(g) + 2OH⁻(aq)   [H⁺/H₂O reduced, not Na⁺]' },
      { type: 'equation', label: 'Anode:', text: '2Cl⁻(aq) → Cl₂(g) + 2e⁻   [Cl⁻ discharged in preference to OH⁻/H₂O because high conc]' },
      { type: 'info', text: 'Products: H₂ at cathode, Cl₂ at anode, and NaOH remains in solution. This is the chlor-alkali process. If dilute NaCl is used, O₂ is produced at the anode instead of Cl₂.' },
      { type: 'heading', text: 'Example 4: Electrolysis of NaOH(aq)' },
      { type: 'equation', label: 'Cathode:', text: '2H₂O(l) + 2e⁻ → H₂(g) + 2OH⁻(aq)' },
      { type: 'equation', label: 'Anode:', text: '4OH⁻(aq) → O₂(g) + 2H₂O(l) + 4e⁻' },
      { type: 'text', text: 'Same products as electrolysis of dilute H₂SO₄: H₂ and O₂ in a 2:1 ratio. Effectively this is the electrolysis of water.' },
    ],
    quiz: [
      { id: 'q1', type: 'mcq', question: 'Aqueous copper(II) sulphate is electrolysed using platinum electrodes. What is produced at the cathode?',
        options: { A: 'Copper', B: 'Hydrogen', C: 'Oxygen', D: 'Sulphur dioxide' },
        answer: 'A', explanation: 'Cu²⁺ is lower in the electrochemical series than H⁺ and is preferentially discharged. Cu²⁺ + 2e⁻ → Cu at the cathode.' },
      { id: 'q2', type: 'mcq', question: 'Concentrated brine (NaCl solution) is electrolysed. What is produced at the anode?',
        options: { A: 'Oxygen', B: 'Chlorine', C: 'Hydrogen', D: 'Sodium' },
        answer: 'B', explanation: 'In concentrated NaCl, Cl⁻ ions are present in high concentration and are preferentially discharged at the anode over OH⁻/H₂O: 2Cl⁻ → Cl₂ + 2e⁻.' },
      { id: 'q3', type: 'mcq', question: 'During the electrolysis of dilute sulphuric acid using platinum electrodes, which gas is produced at the cathode?',
        options: { A: 'Oxygen', B: 'Sulphur dioxide', C: 'Hydrogen', D: 'Sulphur trioxide' },
        answer: 'C', explanation: 'At the cathode, H⁺ ions are reduced: 2H⁺ + 2e⁻ → H₂. SO₄²⁻ is not discharged at the cathode.' },
      { id: 'q4', type: 'structured', question: '(a) Write the half-equation for the reaction at the anode when aqueous CuSO₄ is electrolysed using inert electrodes. (b) State what you would observe at the cathode.',
        hints: ['Anions present: SO₄²⁻ and OH⁻. Which is more easily oxidised?', 'What forms at the cathode?'],
        answer: '(a) 2H₂O(l) → O₂(g) + 4H⁺(aq) + 4e⁻ [1 mark]\n(b) Reddish-brown solid (copper) deposits on the cathode [1 mark]' },
      { id: 'q5', type: 'mcq', question: 'Electrolysis of dilute NaCl solution (not concentrated) is likely to produce which gas at the anode?',
        options: { A: 'Chlorine', B: 'Hydrogen', C: 'Oxygen', D: 'Sodium' },
        answer: 'C', explanation: 'With dilute NaCl, the concentration of Cl⁻ is low relative to OH⁻/H₂O. Water is preferentially oxidised at the anode: 2H₂O → O₂ + 4H⁺ + 4e⁻.' },
      { id: 'q6', type: 'structured', question: 'Explain why the blue colour of copper(II) sulphate solution fades during the electrolysis of CuSO₄(aq) with inert electrodes.',
        hints: ['Blue colour comes from Cu²⁺ ions.', 'What happens to Cu²⁺ at the cathode?'],
        answer: 'Cu²⁺ ions are responsible for the blue colour. At the cathode, Cu²⁺ is reduced to Cu metal and deposited, removing Cu²⁺ from solution. As the concentration of Cu²⁺ decreases, the solution becomes lighter blue and eventually colourless. [2 marks]' },
    ]
  },

  {
    id: 'factors',
    title: 'Factors Affecting Ion Discharge',
    icon: '⚖️',
    time: '30 min',
    topic: 'Factors Affecting Ion Discharge',
    content: [
      { type: 'heading', text: 'Three Main Factors' },
      { type: 'keyPoints', items: [
        '1. Position in the electrochemical series (reduction potential)',
        '2. Concentration of ions in solution',
        '3. Nature of the electrode (active vs. inert)',
      ]},
      { type: 'heading', text: '1. Electrochemical Series (Reduction Potential)' },
      { type: 'text', text: 'For cations at the cathode: ions with a higher (more positive) standard reduction potential are more easily reduced and are preferentially discharged.' },
      { type: 'text', text: 'For anions at the anode: halide ions (Cl⁻, Br⁻, I⁻) are more easily oxidised than SO₄²⁻ or NO₃⁻. The order of ease of discharge at anode: I⁻ > Br⁻ > Cl⁻ > OH⁻ > SO₄²⁻.' },
      { type: 'warn', text: 'The rule "ion lower in the electrochemical series is preferentially discharged at cathode" means: Cu²⁺ is discharged before H⁺, which is discharged before Zn²⁺, which is before Na⁺.' },
      { type: 'heading', text: '2. Concentration Effect' },
      { type: 'text', text: 'Even if an ion is harder to discharge (higher up in the series), if it is present in very high concentration it may be discharged in preference to an ion that is normally easier to discharge but is in low concentration.' },
      { type: 'keyPoints', items: [
        'Concentrated Cl⁻: Cl₂ produced at anode (not O₂)',
        'Dilute Cl⁻: O₂ produced at anode (Cl⁻ too dilute to be preferentially discharged)',
        'This is why industrial brine electrolysis uses concentrated NaCl',
      ]},
      { type: 'heading', text: '3. Nature of Electrode' },
      { type: 'text', text: 'Inert electrodes (carbon/graphite, platinum) do not participate in the electrode reactions — only the ions in solution are discharged.' },
      { type: 'text', text: 'Active electrodes (same metal as the cation being deposited) participate in the reaction. The anode metal dissolves instead of the anion being oxidised.' },
      { type: 'equation', label: 'Active copper anode in CuSO₄(aq):', text: 'Anode: Cu(s) → Cu²⁺(aq) + 2e⁻  (copper dissolves)' },
      { type: 'equation', label: 'Active copper cathode in CuSO₄(aq):', text: 'Cathode: Cu²⁺(aq) + 2e⁻ → Cu(s)  (copper deposits)' },
      { type: 'info', text: 'With active copper electrodes in CuSO₄(aq): the concentration of Cu²⁺ stays constant (as fast as Cu²⁺ is removed at cathode, it is replenished from anode dissolving). This is the basis of copper refining/purification.' },
      { type: 'heading', text: 'Copper Refining (Purification)' },
      { type: 'text', text: 'Impure copper (anode) dissolves. Pure copper deposits on the cathode. Impurities (Zn, Fe — more reactive) dissolve but are not deposited. Impurities (Ag, Au — less reactive) do not dissolve and fall as anode mud. The CuSO₄ solution maintains constant Cu²⁺ concentration.' },
    ],
    quiz: [
      { id: 'q1', type: 'mcq', question: 'Aqueous solution contains both Cu²⁺ and Zn²⁺. Which ion is preferentially discharged at the cathode?',
        options: { A: 'Zn²⁺', B: 'Cu²⁺', C: 'Both equally', D: 'Neither — H₂ is produced' },
        answer: 'B', explanation: 'Cu²⁺ has a higher standard reduction potential (E° = +0.34 V) than Zn²⁺ (E° = −0.76 V). Cu²⁺ is preferentially discharged, forming Cu metal at the cathode.' },
      { id: 'q2', type: 'mcq', question: 'Electrolysis of concentrated NaCl solution produces Cl₂ at the anode, but electrolysis of dilute NaCl produces O₂. This is best explained by:',
        options: { A: 'The nature of the electrode', B: 'The position of Cl⁻ in the electrochemical series', C: 'The concentration of Cl⁻ relative to OH⁻', D: 'The temperature of the solution' },
        answer: 'C', explanation: 'In concentrated solution, Cl⁻ is in large excess and is preferentially discharged. In dilute solution, the relative concentration of OH⁻/H₂O is higher, so water is oxidised to give O₂ instead.' },
      { id: 'q3', type: 'structured', question: 'Copper(II) sulphate solution is electrolysed using (i) platinum electrodes and (ii) copper electrodes. State and explain the difference in the anode reaction in each case.',
        hints: ['What makes an electrode "active"?', 'What happens to the anode metal if it can dissolve?'],
        answer: '(i) Pt (inert): Water is oxidised at the anode: 2H₂O → O₂ + 4H⁺ + 4e⁻. Pt does not participate.\n(ii) Cu (active): The copper anode dissolves: Cu → Cu²⁺ + 2e⁻. It is easier for copper to dissolve than for water to be oxidised. [2 marks]' },
      { id: 'q4', type: 'mcq', question: 'In the electrolytic purification of copper, which statement is correct?',
        options: { A: 'Impure copper is the cathode', B: 'Pure copper is deposited at the anode', C: 'The CuSO₄ solution concentration remains roughly constant', D: 'Precious metal impurities (Au, Ag) dissolve at the anode' },
        answer: 'C', explanation: 'Impure copper (anode) dissolves at the same rate as pure copper deposits at the cathode. The Cu²⁺ concentration stays approximately constant. Gold and silver impurities do not dissolve because they are below Cu in the electrochemical series.' },
    ]
  },

  {
    id: 'quantitative',
    title: "Faraday's Laws of Electrolysis",
    icon: '📐',
    time: '30 min',
    topic: "Faraday's Laws of Electrolysis",
    content: [
      { type: 'heading', text: "Faraday's Laws" },
      { type: 'keyPoints', items: [
        'First Law: The mass of substance deposited/liberated at an electrode is directly proportional to the quantity of electricity (charge) passed.',
        'Second Law: For a given quantity of electricity, the mass of different substances deposited is proportional to their relative atomic mass divided by the number of electrons in the half-equation (equivalent mass, M/z).',
      ]},
      { type: 'heading', text: 'The Faraday Constant' },
      { type: 'equation', label: 'Faraday constant:', text: 'F = 96 500 C mol⁻¹ (charge of 1 mole of electrons)' },
      { type: 'equation', label: 'Charge passed:', text: 'Q = I × t     (Coulombs = Amperes × seconds)' },
      { type: 'equation', label: 'Moles of electrons:', text: 'n(e⁻) = Q / F = (I × t) / F' },
      { type: 'equation', label: 'Moles of substance:', text: 'n(substance) = n(e⁻) / z   where z = electrons per formula unit in the half-equation' },
      { type: 'equation', label: 'Mass deposited:', text: 'm = n × M     where M = molar mass' },
      { type: 'heading', text: 'Worked Example 1' },
      { type: 'text', text: 'A current of 2.0 A is passed through CuSO₄(aq) for 30 minutes using inert electrodes. Calculate the mass of copper deposited at the cathode. (Molar mass of Cu = 63.5 g/mol, F = 96500 C/mol)' },
      { type: 'keyPoints', items: [
        'Q = I × t = 2.0 × (30 × 60) = 3600 C',
        'n(e⁻) = Q / F = 3600 / 96500 = 0.03731 mol',
        'Half-equation: Cu²⁺ + 2e⁻ → Cu, so z = 2',
        'n(Cu) = 0.03731 / 2 = 0.01865 mol',
        'm(Cu) = 0.01865 × 63.5 = 1.19 g',
      ]},
      { type: 'heading', text: 'Worked Example 2' },
      { type: 'text', text: 'What volume of hydrogen gas (at STP: 1 mol gas = 22.4 L) is produced at the cathode when a current of 1.5 A flows through dilute H₂SO₄ for 20 minutes?' },
      { type: 'keyPoints', items: [
        'Q = 1.5 × (20 × 60) = 1800 C',
        'n(e⁻) = 1800 / 96500 = 0.01865 mol',
        'Half-equation: 2H⁺ + 2e⁻ → H₂, so z = 2',
        'n(H₂) = 0.01865 / 2 = 0.009326 mol',
        'V(H₂) = 0.009326 × 22.4 = 0.209 L = 209 mL',
      ]},
      { type: 'heading', text: 'Practical Considerations' },
      { type: 'keyPoints', items: [
        'Current efficiency is rarely 100% — side reactions consume some charge.',
        'Gases must be collected over water or at an inverted electrode.',
        'Check units: time must be in seconds for Q = It.',
        '1 Faraday = charge needed to deposit 1 mole of a monovalent ion (e.g., Ag⁺ → Ag).',
      ]},
    ],
    quiz: [
      { id: 'q1', type: 'mcq', question: 'A current of 3.0 A is passed through molten PbBr₂ for 10 minutes. How many moles of electrons are transferred? (F = 96 500 C/mol)',
        options: { A: '0.019 mol', B: '0.093 mol', C: '0.186 mol', D: '1.86 mol' },
        answer: 'A', explanation: 'Q = 3.0 × 600 = 1800 C; n(e⁻) = 1800 / 96500 = 0.0187 ≈ 0.019 mol' },
      { id: 'q2', type: 'structured', question: 'Calculate the mass of silver deposited when a current of 0.50 A is passed through AgNO₃(aq) for 40 minutes. (Ar of Ag = 108, F = 96 500 C/mol)',
        hints: ['Ag⁺ + e⁻ → Ag, so z = 1.', 'Q = I × t (use seconds)'],
        answer: 'Q = 0.50 × 2400 = 1200 C\nn(e⁻) = 1200/96500 = 0.01244 mol\nz = 1 (Ag⁺ + e⁻ → Ag)\nn(Ag) = 0.01244 mol\nm(Ag) = 0.01244 × 108 = 1.34 g [3 marks]' },
      { id: 'q3', type: 'mcq', question: 'In Faraday\'s Second Law, the quantity M/z is called the:',
        options: { A: 'Molar mass', B: 'Equivalent weight / Equivalent mass', C: 'Atomic number', D: 'Avogadro constant' },
        answer: 'B', explanation: 'M/z (molar mass divided by number of electrons in the half-equation) is the equivalent mass or equivalent weight. Equal charges deposit equal equivalents of any substance.' },
      { id: 'q4', type: 'structured', question: 'The same quantity of electricity is passed through two cells: one containing CuSO₄(aq) and one containing AgNO₃(aq). If 1.27 g of Cu is deposited, calculate the mass of Ag deposited. (Ar: Cu = 63.5, Ag = 108)',
        hints: ['Find n(Cu), then n(e⁻), then n(Ag) using stoichiometry.'],
        answer: 'n(Cu) = 1.27/63.5 = 0.02 mol\nCu²⁺ + 2e⁻ → Cu, so n(e⁻) = 0.04 mol\nAg⁺ + e⁻ → Ag, so n(Ag) = 0.04 mol\nm(Ag) = 0.04 × 108 = 4.32 g [3 marks]' },
    ]
  },

  {
    id: 'applications',
    title: 'Industrial Applications',
    icon: '🏭',
    time: '25 min',
    topic: 'Industrial Applications of Electrolysis',
    content: [
      { type: 'heading', text: 'Electroplating' },
      { type: 'text', text: 'Electroplating deposits a thin layer of metal onto an object for protection, decoration, or to improve conductivity. The object to be plated is the cathode; the plating metal is the anode; the electrolyte contains ions of the plating metal.' },
      { type: 'keyPoints', items: [
        'Object to be plated → cathode (−)',
        'Plating metal → anode (+)',
        'Electrolyte → solution of the plating metal salt',
        'The anode dissolves to maintain ion concentration',
        'Examples: silver plating cutlery (Ag anode in AgNO₃), chrome plating (Cr anode in CrSO₄), nickel plating',
      ]},
      { type: 'equation', label: 'At cathode (object):', text: 'M^n+(aq) + ne⁻ → M(s)  [metal deposits]' },
      { type: 'equation', label: 'At anode (plating metal):', text: 'M(s) → M^n+(aq) + ne⁻  [metal dissolves]' },
      { type: 'heading', text: 'Purification of Copper' },
      { type: 'text', text: 'Impure blister copper (99% Cu with Fe, Zn, Ni, Ag, Au impurities) is refined by electrolysis.' },
      { type: 'keyPoints', items: [
        'Impure copper: anode',
        'Pure copper sheet: cathode',
        'Electrolyte: CuSO₄ solution',
        'Active metals (Fe, Zn, Ni) dissolve from anode but are not deposited (need more negative potential than Cu)',
        'Noble metals (Ag, Au, Pt) do not dissolve — fall as anode slime',
        'Only Cu²⁺ is deposited at cathode → pure copper',
      ]},
      { type: 'heading', text: 'Extraction of Aluminium (Hall-Héroult Process)' },
      { type: 'text', text: 'Al₂O₃ (alumina) has a melting point of ~2072°C. It is dissolved in molten cryolite (Na₃AlF₆) which lowers the operating temperature to ~970°C.' },
      { type: 'equation', label: 'Cathode:', text: 'Al³⁺(l) + 3e⁻ → Al(l)' },
      { type: 'equation', label: 'Anode (carbon):', text: '2O²⁻(l) → O₂(g) + 4e⁻   [or C + O₂ → CO₂]' },
      { type: 'warn', text: 'The carbon anodes gradually burn away due to reaction with oxygen and CO₂ and must be replaced periodically. This is a significant cost.' },
      { type: 'heading', text: 'Chlor-Alkali Process' },
      { type: 'text', text: 'Industrial electrolysis of concentrated brine in membrane cells produces three important chemicals simultaneously.' },
      { type: 'keyPoints', items: [
        'Anode (titanium): 2Cl⁻ → Cl₂ + 2e⁻  → chlorine gas (used to make PVC, bleach, HCl)',
        'Cathode (steel): 2H₂O + 2e⁻ → H₂ + 2OH⁻  → hydrogen gas (fuel) + NaOH solution (caustic soda)',
        'A membrane prevents Cl₂ and NaOH mixing to avoid back-reaction',
      ]},
      { type: 'heading', text: 'Anodizing (Anodisation) of Aluminium' },
      { type: 'text', text: 'The aluminium object is the anode in dilute H₂SO₄. A controlled oxidation produces a thick, adherent Al₂O₃ layer that is corrosion-resistant and can be dyed.' },
      { type: 'equation', label: 'Anode (Al object):', text: '2Al(s) + 3H₂O(l) → Al₂O₃(s) + 6H⁺(aq) + 6e⁻' },
    ],
    quiz: [
      { id: 'q1', type: 'mcq', question: 'In electroplating a spoon with silver, the spoon should be connected as:',
        options: { A: 'Anode, in AgNO₃ solution', B: 'Cathode, in AgNO₃ solution', C: 'Anode, in CuSO₄ solution', D: 'Cathode, in CuSO₄ solution' },
        answer: 'B', explanation: 'The object to be plated (spoon) is the cathode. At the cathode: Ag⁺ + e⁻ → Ag. The silver anode dissolves to replenish Ag⁺. The electrolyte is AgNO₃ (silver salt).' },
      { id: 'q2', type: 'mcq', question: 'In the electrolytic purification of copper, why are gold and silver not deposited at the cathode?',
        options: { A: 'They dissolve at the anode along with copper', B: 'They are removed by the membrane', C: 'They do not dissolve from the impure copper anode', D: 'They have a lower reduction potential than copper' },
        answer: 'C', explanation: 'Gold and silver are below copper in the electrochemical series and are harder to oxidise than copper. They do not dissolve from the anode. Instead, they accumulate as "anode slime" below the anode.' },
      { id: 'q3', type: 'structured', question: 'Why is aluminium oxide dissolved in cryolite rather than electrolysed in its pure molten form in the Hall-Héroult process?',
        hints: ['Consider the energy cost of melting.', 'What does cryolite do to the melting point?'],
        answer: 'Pure Al₂O₃ has a very high melting point (~2072°C), which would require enormous energy and special equipment. Dissolving Al₂O₃ in molten cryolite (Na₃AlF₆) lowers the operating temperature to ~970°C, making the process economically viable. [2 marks]' },
      { id: 'q4', type: 'mcq', question: 'In the chlor-alkali process, a membrane is used between the two electrode compartments. The purpose of the membrane is to:',
        options: { A: 'Prevent electrons from crossing', B: 'Prevent Cl₂ and NaOH from mixing', C: 'Increase the concentration of NaCl', D: 'Allow Na⁺ and Cl⁻ ions to freely mix' },
        answer: 'B', explanation: 'Cl₂ gas and NaOH solution would react with each other if mixed: Cl₂ + 2NaOH → NaCl + NaOCl + H₂O. The ion-exchange membrane allows Na⁺ to pass but prevents the Cl⁻ from crossing to the cathode compartment.' },
    ]
  },

  {
    id: 'voltaic',
    title: 'Voltaic Cells',
    icon: '🔋',
    time: '30 min',
    topic: 'Voltaic Cells',
    content: [
      { type: 'heading', text: 'Voltaic Cell Principles' },
      { type: 'text', text: 'A voltaic (galvanic) cell converts chemical energy from a spontaneous redox reaction into electrical energy. Unlike electrolytic cells, no external power is needed.' },
      { type: 'keyPoints', items: [
        'The more reactive metal acts as the anode (negative terminal) — it oxidises and dissolves.',
        'The less reactive metal is the cathode (positive terminal) — cations are reduced and deposited.',
        'Electrons flow from anode to cathode through the external circuit.',
        'In the electrolyte, cations migrate toward the cathode; anions toward the anode.',
      ]},
      { type: 'warn', text: 'In a voltaic cell, the anode is NEGATIVE (electrons flow out from it). This is OPPOSITE to an electrolytic cell where the anode is POSITIVE. This often confuses students.' },
      { type: 'heading', text: 'Simple Zinc-Copper Cell' },
      { type: 'text', text: 'A zinc plate in ZnSO₄ solution and a copper plate in CuSO₄ solution, connected by a wire and a salt bridge.' },
      { type: 'equation', label: 'Anode (Zn, negative):', text: 'Zn(s) → Zn²⁺(aq) + 2e⁻  (oxidation)' },
      { type: 'equation', label: 'Cathode (Cu, positive):', text: 'Cu²⁺(aq) + 2e⁻ → Cu(s)  (reduction)' },
      { type: 'equation', label: 'Overall:', text: 'Zn(s) + Cu²⁺(aq) → Zn²⁺(aq) + Cu(s)' },
      { type: 'info', text: 'EMF = E°(cathode) − E°(anode) = (+0.34) − (−0.76) = +1.10 V' },
      { type: 'heading', text: 'The Salt Bridge' },
      { type: 'text', text: 'The salt bridge (e.g., KNO₃ in agar gel) completes the electrical circuit by allowing ions to migrate between the two half-cells without mixing the solutions.' },
      { type: 'keyPoints', items: [
        'Without the salt bridge, charge would build up in each half-cell, stopping the flow of electrons.',
        'Cations from the salt bridge migrate toward the cathode half-cell (to compensate for Cu²⁺ being consumed).',
        'Anions from the salt bridge migrate toward the anode half-cell (to neutralise the positive charge building up as Zn²⁺ is produced).',
      ]},
      { type: 'heading', text: 'Predicting Which Metal is the Anode' },
      { type: 'text', text: 'The more reactive metal (higher in reactivity series / more negative E°) acts as the anode (is oxidised). Use the electrochemical series: a metal higher up will displace (oxidise in preference to) one lower down.' },
      { type: 'table', headers: ['Metal pair', 'Anode', 'Cathode'],
        rows: [
          ['Zn and Cu', 'Zn (more reactive)', 'Cu (less reactive)'],
          ['Fe and Cu', 'Fe (more reactive)', 'Cu (less reactive)'],
          ['Mg and Fe', 'Mg (more reactive)', 'Fe (less reactive)'],
          ['Cu and Ag', 'Cu (more reactive)', 'Ag (less reactive)'],
        ]
      },
    ],
    quiz: [
      { id: 'q1', type: 'mcq', question: 'In a voltaic cell made of magnesium and copper, which electrode is the anode?',
        options: { A: 'Copper', B: 'Magnesium', C: 'Both are anodes', D: 'It depends on the electrolyte' },
        answer: 'B', explanation: 'Magnesium is more reactive than copper. In a voltaic cell, the more reactive metal is oxidised at the anode: Mg → Mg²⁺ + 2e⁻.' },
      { id: 'q2', type: 'mcq', question: 'Electrons in the external circuit of a voltaic cell flow from:',
        options: { A: 'Cathode to anode', B: 'Positive terminal to cathode', C: 'Anode (negative) to cathode (positive)', D: 'Inside the electrolyte' },
        answer: 'C', explanation: 'In a voltaic cell, the anode is the negative terminal (metal dissolves, releasing electrons). Electrons flow through the external wire from the anode to the cathode (positive terminal).' },
      { id: 'q3', type: 'structured', question: 'A voltaic cell is set up with iron (Fe) and silver (Ag) electrodes in appropriate electrolyte solutions. (a) Identify the anode and cathode. (b) Write the half-equation at each electrode.',
        hints: ['Fe is higher (more reactive) in the electrochemical series than Ag.', 'Anode = oxidation; cathode = reduction.'],
        answer: '(a) Anode: Fe (more reactive); Cathode: Ag\n(b) Anode: Fe(s) → Fe²⁺(aq) + 2e⁻\n    Cathode: Ag⁺(aq) + e⁻ → Ag(s)  [or: 2Ag⁺ + 2e⁻ → 2Ag] [3 marks]' },
      { id: 'q4', type: 'mcq', question: 'What is the function of the salt bridge in a Daniel cell?',
        options: { A: 'To allow electrons to flow between the half-cells', B: 'To allow ions to migrate and maintain electrical neutrality in each half-cell', C: 'To prevent any ionic mixing', D: 'To increase the EMF of the cell' },
        answer: 'B', explanation: 'The salt bridge allows ions (not electrons) to migrate between the two half-cells to maintain electrical neutrality. Without it, positive charge would build up in the anode compartment and negative charge in the cathode compartment, stopping current flow.' },
    ]
  },

  {
    id: 'daniel',
    title: 'The Daniel Cell & EMF',
    icon: '🔌',
    time: '30 min',
    topic: 'The Daniel Cell and EMF',
    content: [
      { type: 'heading', text: 'The Daniel Cell' },
      { type: 'text', text: 'The Daniel cell is a classic voltaic cell with Zn in ZnSO₄(aq) and Cu in CuSO₄(aq), connected by a salt bridge (often KNO₃ or KCl in agar).' },
      { type: 'keyPoints', items: [
        'Zn electrode in ZnSO₄ — the anode (negative, −0.76 V)',
        'Cu electrode in CuSO₄ — the cathode (positive, +0.34 V)',
        'Salt bridge connects the two solutions',
        'Voltmeter or external circuit connects the electrodes',
      ]},
      { type: 'equation', label: 'Anode (oxidation):', text: 'Zn(s) → Zn²⁺(aq) + 2e⁻        E° = +0.76 V (as oxidation)' },
      { type: 'equation', label: 'Cathode (reduction):', text: 'Cu²⁺(aq) + 2e⁻ → Cu(s)     E°red = +0.34 V' },
      { type: 'equation', label: 'Cell EMF:', text: 'E°cell = E°cathode − E°anode = (+0.34) − (−0.76) = +1.10 V' },
      { type: 'heading', text: 'Standard Electrode Potentials (E°)' },
      { type: 'text', text: 'Standard electrode potentials are measured relative to the standard hydrogen electrode (SHE, E° = 0.00 V) under standard conditions (25°C, 1 M, 1 atm).' },
      { type: 'table', headers: ['Half-reaction (reduction)', 'E° (V)'],
        rows: [
          ['F₂ + 2e⁻ → 2F⁻', '+2.87'],
          ['MnO₄⁻ + 8H⁺ + 5e⁻ → Mn²⁺ + 4H₂O', '+1.51'],
          ['Cl₂ + 2e⁻ → 2Cl⁻', '+1.36'],
          ['O₂ + 4H⁺ + 4e⁻ → 2H₂O', '+1.23'],
          ['Ag⁺ + e⁻ → Ag', '+0.80'],
          ['Cu²⁺ + 2e⁻ → Cu', '+0.34'],
          ['2H⁺ + 2e⁻ → H₂', '0.00 (SHE)'],
          ['Pb²⁺ + 2e⁻ → Pb', '−0.13'],
          ['Ni²⁺ + 2e⁻ → Ni', '−0.25'],
          ['Fe²⁺ + 2e⁻ → Fe', '−0.44'],
          ['Zn²⁺ + 2e⁻ → Zn', '−0.76'],
          ['Mg²⁺ + 2e⁻ → Mg', '−2.37'],
          ['Na⁺ + e⁻ → Na', '−2.71'],
          ['K⁺ + e⁻ → K', '−2.93'],
        ]
      },
      { type: 'heading', text: 'Predicting Cell EMF and Feasibility' },
      { type: 'text', text: 'A positive E°cell means the reaction is spontaneous (will produce electricity). A negative E°cell means the reaction is non-spontaneous (needs energy input).' },
      { type: 'equation', label: 'Rule:', text: 'E°cell = E°(cathode, reduction) − E°(anode, reduction)\nIf E°cell > 0 → spontaneous → voltaic cell possible' },
      { type: 'info', text: 'The species with the more positive E°red value is preferentially reduced (acts as cathode). The species with the more negative E°red acts as anode (is oxidised).' },
    ],
    quiz: [
      { id: 'q1', type: 'structured', question: 'Calculate the standard EMF of a cell made from Ag/Ag⁺ and Fe/Fe²⁺ half-cells. State which electrode is the anode and write the overall cell equation.',
        hints: ['E°(Ag⁺/Ag) = +0.80 V, E°(Fe²⁺/Fe) = −0.44 V', 'Cathode = more positive E°'],
        answer: 'Cathode: Ag (E° = +0.80 V); Anode: Fe (E° = −0.44 V)\nE°cell = 0.80 − (−0.44) = +1.24 V\nAnode: Fe → Fe²⁺ + 2e⁻\nCathode: 2Ag⁺ + 2e⁻ → 2Ag\nOverall: Fe + 2Ag⁺ → Fe²⁺ + 2Ag [3 marks]' },
      { id: 'q2', type: 'mcq', question: 'Which pair of half-cells would produce the greatest EMF?',
        options: { A: 'Cu/Cu²⁺ and Ag/Ag⁺', B: 'Zn/Zn²⁺ and Cu/Cu²⁺', C: 'Mg/Mg²⁺ and Cu/Cu²⁺', D: 'Fe/Fe²⁺ and Ni/Ni²⁺' },
        answer: 'C', explanation: 'E°cell = E°(Cu²⁺/Cu) − E°(Mg²⁺/Mg) = (+0.34) − (−2.37) = +2.71 V. This is the largest difference among the options.' },
      { id: 'q3', type: 'mcq', question: 'A cell has E°cell = −0.50 V. This means:',
        options: { A: 'The reaction is spontaneous', B: 'The reaction is non-spontaneous under standard conditions', C: 'No current can flow', D: 'The reaction produces 0.50 V' },
        answer: 'B', explanation: 'A negative E°cell indicates that the reaction as written is non-spontaneous. Energy would need to be supplied (as in electrolysis) to drive this reaction forward.' },
      { id: 'q4', type: 'mcq', question: 'In a Daniel cell at equilibrium (no current flowing), the EMF is:',
        options: { A: 'Greater than 1.10 V', B: 'Exactly 1.10 V (if standard)', C: 'Zero', D: 'Negative' },
        answer: 'B', explanation: 'At standard conditions (1 M concentrations, 25°C), the EMF of the Daniel cell is +1.10 V. As the cell operates and concentrations change, the EMF decreases from this value according to the Nernst equation.' },
    ]
  },

  {
    id: 'fuel',
    title: 'Fuel Cells',
    icon: '🌿',
    time: '20 min',
    topic: 'Fuel Cells',
    content: [
      { type: 'heading', text: 'Hydrogen-Oxygen Fuel Cell' },
      { type: 'text', text: 'A fuel cell converts chemical energy from a fuel (H₂) and an oxidant (O₂) directly into electrical energy. The overall reaction is: 2H₂ + O₂ → 2H₂O.' },
      { type: 'text', text: 'Unlike batteries, fuel cells do not store energy — they produce it continuously as long as fuel is supplied. The electrolyte can be alkaline (KOH) or acidic (H₂SO₄/proton-exchange membrane).' },
      { type: 'heading', text: 'Alkaline Fuel Cell (KOH electrolyte)' },
      { type: 'equation', label: 'Anode (H₂ oxidised):', text: 'H₂(g) + 2OH⁻(aq) → 2H₂O(l) + 2e⁻' },
      { type: 'equation', label: 'Cathode (O₂ reduced):', text: 'O₂(g) + 2H₂O(l) + 4e⁻ → 4OH⁻(aq)' },
      { type: 'equation', label: 'Overall:', text: '2H₂(g) + O₂(g) → 2H₂O(l)' },
      { type: 'heading', text: 'Acidic Fuel Cell / PEMFC (H₂SO₄ or PEM)' },
      { type: 'equation', label: 'Anode:', text: 'H₂(g) → 2H⁺(aq) + 2e⁻' },
      { type: 'equation', label: 'Cathode:', text: 'O₂(g) + 4H⁺(aq) + 4e⁻ → 2H₂O(l)' },
      { type: 'heading', text: 'Advantages and Disadvantages' },
      { type: 'table', headers: ['Advantages', 'Disadvantages'],
        rows: [
          ['Only product is water (no CO₂)', 'H₂ storage and distribution is difficult'],
          ['High efficiency (~60% vs ~25% internal combustion)', 'Expensive catalysts (platinum)'],
          ['Continuous operation (no recharging)', 'H₂ is currently mostly made from fossil fuels'],
          ['Silent operation', 'Hydrogen is flammable and explosive'],
          ['No moving parts (in PEMFC)', 'Infrastructure not yet widespread'],
        ]
      },
      { type: 'heading', text: 'Comparison with Other Cells' },
      { type: 'table', headers: ['Feature', 'Battery', 'Fuel Cell'],
        rows: [
          ['Energy storage', 'Internal (finite)', 'External fuel (continuous)'],
          ['Recharging', 'Required (for rechargeable)', 'Not needed — refuel'],
          ['Exhaust', 'None (closed system)', 'Water (from H₂/O₂)'],
          ['Weight/energy ratio', 'Lower', 'Higher (without tank)'],
        ]
      },
    ],
    quiz: [
      { id: 'q1', type: 'mcq', question: 'In an alkaline hydrogen-oxygen fuel cell, what is the product at the cathode?',
        options: { A: 'Hydrogen gas', B: 'Oxygen gas', C: 'Hydroxide ions', D: 'Water' },
        answer: 'C', explanation: 'At the cathode of an alkaline fuel cell: O₂ + 2H₂O + 4e⁻ → 4OH⁻. Hydroxide ions are produced, which then participate in the anode reaction.' },
      { id: 'q2', type: 'mcq', question: 'A major advantage of hydrogen fuel cells over petrol engines is:',
        options: { A: 'Lower initial cost', B: 'Greater energy output per gram of fuel', C: 'The only exhaust product is water', D: 'Hydrogen is widely available' },
        answer: 'C', explanation: 'The overall reaction of a hydrogen-oxygen fuel cell is 2H₂ + O₂ → 2H₂O. The only exhaust is water vapour, making it zero-emission at the point of use.' },
      { id: 'q3', type: 'structured', question: 'Write the half-equation for the oxidation of hydrogen at the anode in an acidic (H₂SO₄) hydrogen-oxygen fuel cell.',
        hints: ['Oxidation means losing electrons.', 'In acidic conditions, what are the products of H₂ oxidation?'],
        answer: 'H₂(g) → 2H⁺(aq) + 2e⁻ [1 mark — must show state symbols for full marks in HKDSE]' },
      { id: 'q4', type: 'mcq', question: 'Unlike a conventional battery, a fuel cell:',
        options: { A: 'Does not require an electrolyte', B: 'Can operate continuously without recharging as long as fuel is supplied', C: 'Has a higher self-discharge rate', D: 'Produces AC electricity' },
        answer: 'B', explanation: 'A fuel cell operates as long as fuel (H₂) and oxidant (O₂) are supplied externally. It does not store chemical energy internally like a battery, so it does not need to be recharged — only refuelled.' },
    ]
  },
]
