// Bilingual lesson content. Every natural-language string is a { en, zh } node.
// Chemical formulae, half-equations, units and numbers are language-neutral and
// stored as plain strings. Rendered via the `pick()` helper from LanguageContext.

export const LESSONS = [
  {
    id: 'intro',
    title: { en: 'Introduction to Electrolysis', zh: '電解導論' },
    icon: '⚡',
    time: '20 min',
    topic: { en: 'Introduction to Electrolysis', zh: '電解導論' },
    content: [
      { type: 'heading', text: { en: 'What is Electrolysis?', zh: '甚麼是電解？' } },
      { type: 'text', text: { en: 'Electrolysis is the process of using electrical energy to drive a non-spontaneous chemical reaction — specifically, the decomposition of an ionic compound (the electrolyte) into its constituent elements.', zh: '電解是利用電能推動非自發化學反應的過程 —— 具體而言，是把離子化合物（電解質）分解成其組成元素。' } },
      { type: 'keyPoints', items: [
        { en: 'Electrolyte: an ionic compound that conducts electricity when molten or dissolved in water.', zh: '電解質：在熔融或溶於水時能導電的離子化合物。' },
        { en: 'Non-electrolytes: covalent compounds that cannot conduct electricity (e.g. sugar, ethanol).', zh: '非電解質：不能導電的共價化合物（例如糖、乙醇）。' },
        { en: 'Electrical energy breaks the ionic bonds and causes ions to discharge at the electrodes.', zh: '電能拆散離子鍵，使離子在電極上放電。' },
      ] },
      { type: 'heading', text: { en: 'Conductors of Electricity', zh: '電的導體' } },
      { type: 'table',
        headers: [{ en: 'Type', zh: '類型' }, { en: 'Examples', zh: '例子' }, { en: 'Charge Carriers', zh: '載流子' }],
        rows: [
          [{ en: 'Metallic conductors', zh: '金屬導體' }, { en: 'Cu, Fe, graphite', zh: 'Cu、Fe、石墨' }, { en: 'Delocalised electrons', zh: '離域電子' }],
          [{ en: 'Electrolytic conductors', zh: '電解導體' }, { en: 'NaCl(aq), CuSO₄(aq), molten KBr', zh: 'NaCl(aq)、CuSO₄(aq)、熔融 KBr' }, { en: 'Mobile ions', zh: '可移動離子' }],
          [{ en: 'Non-conductors', zh: '非導體' }, { en: 'Sugar solution, distilled water, solid NaCl', zh: '糖溶液、蒸餾水、固態 NaCl' }, { en: 'None', zh: '沒有' }],
        ] },
      { type: 'heading', text: { en: 'The Electrolytic Cell', zh: '電解池' } },
      { type: 'text', text: { en: 'An electrolytic cell consists of a DC power supply (battery), two electrodes submerged in the electrolyte, and the electrolyte itself.', zh: '電解池由直流電源（電池）、兩個浸於電解質中的電極，以及電解質本身組成。' } },
      { type: 'keyPoints', items: [
        { en: 'Anode (+): connected to the positive terminal of the battery. Oxidation occurs here.', zh: '陽極（+）：接駁電池正極。氧化在此發生。' },
        { en: 'Cathode (−): connected to the negative terminal. Reduction occurs here.', zh: '陰極（−）：接駁電池負極。還原在此發生。' },
        { en: 'Anions (negative ions) migrate toward the anode.', zh: '陰離子（帶負電）遷向陽極。' },
        { en: 'Cations (positive ions) migrate toward the cathode.', zh: '陽離子（帶正電）遷向陰極。' },
      ] },
      { type: 'equation', label: { en: 'Memory aid', zh: '記憶法' }, text: 'AN OX — RED CAT: ANode = OXidation, REDuction = CAThode' },
      { type: 'heading', text: { en: 'Electron Flow', zh: '電子流動' } },
      { type: 'text', text: { en: 'Electrons are produced at the anode (when anions are oxidised) and travel through the external wires to the cathode, where they reduce the cations. Inside the electrolyte, charge is carried by moving ions, not electrons.', zh: '電子在陽極產生（陰離子被氧化時），經外電路的導線流到陰極，在該處還原陽離子。在電解質內部，電荷由移動的離子（而非電子）傳送。' } },
      { type: 'equation', label: { en: 'Electron flow', zh: '電子流向' }, text: 'Electrons: − terminal → cathode … anode → + terminal (through external wire only)' },
      { type: 'warn', text: { en: 'Common mistake: students often say electrons flow through the electrolyte. They do NOT — only ions move inside the solution.', zh: '常見錯誤：學生常說電子在電解質中流動。並非如此 —— 溶液內只有離子移動。' } },
      { type: 'heading', text: { en: 'Electrolytic vs Voltaic Cells', zh: '電解池與伏打電池的比較' } },
      { type: 'table',
        headers: [{ en: 'Feature', zh: '特徵' }, { en: 'Electrolytic Cell', zh: '電解池' }, { en: 'Voltaic Cell', zh: '伏打電池' }],
        rows: [
          [{ en: 'Energy conversion', zh: '能量轉換' }, { en: 'Electrical → Chemical', zh: '電能 → 化學能' }, { en: 'Chemical → Electrical', zh: '化學能 → 電能' }],
          [{ en: 'External power', zh: '外接電源' }, { en: 'Required', zh: '需要' }, { en: 'Not needed', zh: '不需要' }],
          [{ en: 'Anode charge', zh: '陽極電性' }, { en: 'Positive (+)', zh: '正（+）' }, { en: 'Negative (−)', zh: '負（−）' }],
          [{ en: 'Cathode charge', zh: '陰極電性' }, { en: 'Negative (−)', zh: '負（−）' }, { en: 'Positive (+)', zh: '正（+）' }],
          [{ en: 'Spontaneity', zh: '自發性' }, { en: 'Non-spontaneous', zh: '非自發' }, { en: 'Spontaneous', zh: '自發' }],
        ] },
    ],
    quiz: [
      { id: 'q1', type: 'mcq',
        question: { en: 'Which of the following can conduct electricity in the solid state?', zh: '下列哪項在固態時能導電？' },
        options: { A: { en: 'Sodium chloride (NaCl)', zh: '氯化鈉 (NaCl)' }, B: { en: 'Copper wire', zh: '銅線' }, C: { en: 'Sugar (C₁₂H₂₂O₁₁)', zh: '蔗糖 (C₁₂H₂₂O₁₁)' }, D: { en: 'Distilled water', zh: '蒸餾水' } },
        answer: 'B',
        explanation: { en: 'Metallic conductors like copper have delocalised electrons that carry charge. Solid NaCl has no mobile ions; sugar and distilled water have no charge carriers.', zh: '像銅的金屬導體有離域電子傳送電荷。固態 NaCl 沒有可移動離子；糖和蒸餾水沒有載流子。' } },
      { id: 'q2', type: 'mcq',
        question: { en: 'During electrolysis, which process occurs at the cathode?', zh: '電解過程中，陰極發生哪個過程？' },
        options: { A: { en: 'Oxidation of anions', zh: '陰離子氧化' }, B: { en: 'Reduction of cations', zh: '陽離子還原' }, C: { en: 'Oxidation of cations', zh: '陽離子氧化' }, D: { en: 'Reduction of anions', zh: '陰離子還原' } },
        answer: 'B',
        explanation: { en: 'The cathode is negative and attracts cations. Electrons arrive from the external circuit, so cations gain electrons — they are reduced (RED CAT).', zh: '陰極帶負電，吸引陽離子。電子由外電路到達，陽離子得到電子而被還原（RED CAT）。' } },
      { id: 'q3', type: 'mcq',
        question: { en: 'An aqueous solution of copper(II) sulfate does NOT conduct electricity when:', zh: '硫酸銅(II)水溶液在下列哪種情況下不會導電？' },
        options: { A: { en: 'It is diluted with water', zh: '被水稀釋' }, B: { en: 'The copper sulfate is not dissolved', zh: '硫酸銅未溶解' }, C: { en: 'The temperature is raised', zh: '溫度上升' }, D: { en: 'More copper sulfate is dissolved', zh: '溶解更多硫酸銅' } },
        answer: 'B',
        explanation: { en: 'Conductivity needs mobile ions. Only when dissolved (or molten) can the ions move. Solid CuSO₄ has no mobile ions.', zh: '導電需要可移動離子。只有溶解（或熔融）時離子才能移動。固態 CuSO₄ 沒有可移動離子。' } },
      { id: 'q4', type: 'structured',
        question: { en: 'Explain, with reference to charge carriers, why solid sodium chloride does not conduct electricity but molten sodium chloride does.', zh: '就載流子解釋為何固態氯化鈉不導電，而熔融氯化鈉能導電。' },
        hints: [{ en: 'Think about where the ions are in each state.', zh: '想想離子在各狀態的位置。' }, { en: 'What allows charge carriers to move?', zh: '甚麼使載流子能移動？' }],
        answer: { en: 'In solid NaCl the Na⁺ and Cl⁻ ions are held in a fixed lattice and cannot move, so there are no mobile charge carriers and it does not conduct. In molten NaCl the lattice breaks down, allowing the ions to move freely and carry charge. (2 marks)', zh: '固態 NaCl 中 Na⁺ 和 Cl⁻ 固定於晶格內不能移動，沒有可移動載流子，故不導電。熔融 NaCl 中晶格瓦解，離子可自由移動並傳送電荷，故能導電。（2 分）' } },
      { id: 'q5', type: 'mcq',
        question: { en: 'Electrons in the external circuit of an electrolytic cell flow from:', zh: '電解池外電路中的電子由何處流向何處？' },
        options: { A: { en: 'Cathode to anode', zh: '陰極流向陽極' }, B: { en: 'Positive terminal of battery to anode', zh: '電池正極流向陽極' }, C: { en: 'Anode to cathode through the electrolyte', zh: '陽極經電解質流向陰極' }, D: { en: 'Anode to cathode through the external wire', zh: '陽極經外導線流向陰極' } },
        answer: 'D',
        explanation: { en: 'Electrons are produced by oxidation at the anode and flow through the external wire to the cathode. They cannot flow through the electrolyte — only ions move there.', zh: '電子由陽極的氧化反應產生，經外導線流到陰極。電子不能在電解質中流動 —— 該處只有離子移動。' } },
    ],
  },

  {
    id: 'molten',
    title: { en: 'Electrolysis of Molten Salts', zh: '熔融鹽的電解' },
    icon: '🔥',
    time: '25 min',
    topic: { en: 'Electrolysis of Molten Salts', zh: '熔融鹽的電解' },
    content: [
      { type: 'heading', text: { en: 'Why Molten Salts?', zh: '為何用熔融鹽？' } },
      { type: 'text', text: { en: 'When an ionic solid is melted, its ions become mobile. This is the simplest case of electrolysis because only two kinds of ion are present — no water molecules to complicate matters.', zh: '離子固體熔化後，離子變得可移動。這是最簡單的電解情況，因為只有兩種離子 —— 沒有水分子造成複雜情況。' } },
      { type: 'heading', text: { en: 'Electrolysis of Molten Lead(II) Bromide (PbBr₂)', zh: '熔融溴化鉛(II) (PbBr₂) 的電解' } },
      { type: 'text', text: { en: 'Molten PbBr₂ contains Pb²⁺ and Br⁻ ions. On electrolysis:', zh: '熔融 PbBr₂ 含有 Pb²⁺ 和 Br⁻ 離子。電解時：' } },
      { type: 'keyPoints', items: [
        { en: 'Pb²⁺ (cations) migrate to the cathode.', zh: 'Pb²⁺（陽離子）遷向陰極。' },
        { en: 'Br⁻ (anions) migrate to the anode.', zh: 'Br⁻（陰離子）遷向陽極。' },
        { en: 'At the cathode: Pb²⁺ is reduced to grey liquid lead.', zh: '陰極：Pb²⁺ 被還原成灰色液態鉛。' },
        { en: 'At the anode: Br⁻ is oxidised to brown/orange bromine vapour.', zh: '陽極：Br⁻ 被氧化成棕／橙色溴蒸氣。' },
      ] },
      { type: 'equation', label: { en: 'Cathode (reduction):', zh: '陰極（還原）：' }, text: 'Pb²⁺(l) + 2e⁻ → Pb(l)' },
      { type: 'equation', label: { en: 'Anode (oxidation):', zh: '陽極（氧化）：' }, text: '2Br⁻(l) → Br₂(g) + 2e⁻' },
      { type: 'equation', label: { en: 'Overall:', zh: '總反應：' }, text: 'PbBr₂(l) → Pb(l) + Br₂(g)' },
      { type: 'info', text: { en: 'Grey liquid metal appears at the cathode; brown/orange fumes at the anode. The electrolyte fades as Br⁻ is consumed.', zh: '陰極出現灰色液態金屬；陽極出現棕／橙色煙霧。隨 Br⁻ 被消耗，電解質顏色變淡。' } },
      { type: 'heading', text: { en: 'Molten Sodium Chloride (NaCl)', zh: '熔融氯化鈉 (NaCl)' } },
      { type: 'equation', label: { en: 'Cathode:', zh: '陰極：' }, text: 'Na⁺(l) + e⁻ → Na(l)' },
      { type: 'equation', label: { en: 'Anode:', zh: '陽極：' }, text: '2Cl⁻(l) → Cl₂(g) + 2e⁻' },
      { type: 'text', text: { en: 'Sodium metal forms at the cathode and chlorine gas (yellow-green) at the anode. This is the industrial basis for producing sodium and chlorine.', zh: '陰極生成鈉金屬，陽極生成氯氣（黃綠色）。這是工業製鈉和氯的基礎。' } },
      { type: 'heading', text: { en: 'General Pattern', zh: '通則' } },
      { type: 'table',
        headers: [{ en: 'Electrolyte', zh: '電解質' }, { en: 'Cathode product', zh: '陰極產物' }, { en: 'Anode product', zh: '陽極產物' }],
        rows: [
          [{ en: 'Molten PbBr₂', zh: '熔融 PbBr₂' }, { en: 'Lead (grey)', zh: '鉛（灰色）' }, { en: 'Bromine (brown)', zh: '溴（棕色）' }],
          [{ en: 'Molten NaCl', zh: '熔融 NaCl' }, { en: 'Sodium', zh: '鈉' }, { en: 'Chlorine', zh: '氯' }],
          [{ en: 'Molten MgCl₂', zh: '熔融 MgCl₂' }, { en: 'Magnesium', zh: '鎂' }, { en: 'Chlorine', zh: '氯' }],
          [{ en: 'Molten Al₂O₃', zh: '熔融 Al₂O₃' }, { en: 'Aluminium', zh: '鋁' }, { en: 'Oxygen', zh: '氧' }],
        ] },
      { type: 'warn', text: { en: 'The cathode product is always the metal of the compound; the anode product comes from the anion (Cl⁻→Cl₂, Br⁻→Br₂, O²⁻→O₂).', zh: '陰極產物必為化合物中的金屬；陽極產物來自陰離子（Cl⁻→Cl₂、Br⁻→Br₂、O²⁻→O₂）。' } },
      { type: 'heading', text: { en: 'Why High Temperature?', zh: '為何需高溫？' } },
      { type: 'text', text: { en: 'The solid must be fully melted so the ions have enough thermal energy to move through the melt. Below the melting point the ions are locked in the lattice and electrolysis cannot occur.', zh: '固體必須完全熔化，使離子有足夠熱能在熔體中移動。低於熔點時離子鎖在晶格內，電解無法進行。' } },
    ],
    quiz: [
      { id: 'q1', type: 'mcq',
        question: { en: 'Molten lead(II) bromide is electrolysed with carbon electrodes. What is observed at the anode?', zh: '以碳電極電解熔融溴化鉛(II)，陽極有何觀察？' },
        options: { A: { en: 'Grey solid deposits', zh: '沉積灰色固體' }, B: { en: 'Colourless gas', zh: '無色氣體' }, C: { en: 'Brown fumes', zh: '棕色煙霧' }, D: { en: 'The electrode dissolves', zh: '電極溶解' } },
        answer: 'C',
        explanation: { en: 'At the anode Br⁻ is oxidised to Br₂ (2Br⁻ → Br₂ + 2e⁻), a brown/orange vapour.', zh: '陽極 Br⁻ 被氧化成 Br₂（2Br⁻ → Br₂ + 2e⁻），為棕／橙色蒸氣。' } },
      { id: 'q2', type: 'mcq',
        question: { en: 'In the electrolysis of molten NaCl, what forms at the cathode?', zh: '電解熔融 NaCl 時，陰極生成甚麼？' },
        options: { A: { en: 'Chlorine gas', zh: '氯氣' }, B: { en: 'Sodium metal', zh: '鈉金屬' }, C: { en: 'Hydrogen gas', zh: '氫氣' }, D: { en: 'Oxygen gas', zh: '氧氣' } },
        answer: 'B',
        explanation: { en: 'Na⁺ is the only cation. At the cathode Na⁺ + e⁻ → Na. No water is present, so no H₂ forms.', zh: 'Na⁺ 是唯一陽離子。陰極 Na⁺ + e⁻ → Na。沒有水，故不會生成 H₂。' } },
      { id: 'q3', type: 'structured',
        question: { en: 'Write the ionic half-equations for the electrode reactions when molten MgCl₂ is electrolysed.', zh: '寫出電解熔融 MgCl₂ 時各電極反應的離子半反應方程式。' },
        hints: [{ en: 'MgCl₂ contains Mg²⁺ and Cl⁻.', zh: 'MgCl₂ 含 Mg²⁺ 及 Cl⁻。' }, { en: 'Which ion goes to which electrode?', zh: '哪種離子到哪個電極？' }],
        answer: { en: 'Cathode: Mg²⁺(l) + 2e⁻ → Mg(l) [1]\nAnode: 2Cl⁻(l) → Cl₂(g) + 2e⁻ [1]', zh: '陰極：Mg²⁺(l) + 2e⁻ → Mg(l)（1 分）\n陽極：2Cl⁻(l) → Cl₂(g) + 2e⁻（1 分）' } },
      { id: 'q4', type: 'mcq',
        question: { en: 'Why is solid NaCl not used in place of molten NaCl for electrolysis?', zh: '為何不能用固態 NaCl 代替熔融 NaCl 進行電解？' },
        options: { A: { en: 'Solid NaCl has no ions', zh: '固態 NaCl 沒有離子' }, B: { en: 'Ions in solid NaCl are not mobile', zh: '固態 NaCl 的離子不能移動' }, C: { en: 'Solid NaCl decomposes on heating', zh: '固態 NaCl 受熱分解' }, D: { en: 'Its melting point is too low', zh: '其熔點太低' } },
        answer: 'B',
        explanation: { en: 'Solid NaCl contains ions but they are fixed in the lattice. Electrolysis needs mobile charge carriers, which exist only once melted.', zh: '固態 NaCl 含離子但固定於晶格。電解需要可移動載流子，只有熔化後才存在。' } },
      { id: 'q5', type: 'mcq',
        question: { en: 'What is the role of the electrons transferred in the external circuit during electrolysis?', zh: '電解時外電路傳遞的電子有何作用？' },
        options: { A: { en: 'Carry charge through the electrolyte', zh: '在電解質中傳送電荷' }, B: { en: 'Convert cations to anions', zh: '把陽離子變成陰離子' }, C: { en: 'Enable reduction at the cathode and oxidation at the anode', zh: '使陰極還原、陽極氧化' }, D: { en: 'Heat the electrolyte', zh: '加熱電解質' } },
        answer: 'C',
        explanation: { en: 'Electrons leave the anode (oxidation) into the circuit and arrive at the cathode (reduction of cations).', zh: '電子由陽極（氧化）進入電路，到達陰極（還原陽離子）。' } },
    ],
  },

  {
    id: 'aqueous',
    title: { en: 'Electrolysis of Aqueous Solutions', zh: '水溶液的電解' },
    icon: '💧',
    time: '35 min',
    topic: { en: 'Electrolysis of Aqueous Solutions', zh: '水溶液的電解' },
    content: [
      { type: 'heading', text: { en: 'The Complication: Water', zh: '複雜之處：水' } },
      { type: 'text', text: { en: 'Aqueous solutions contain both the dissolved ions AND water molecules. Water itself can be oxidised at the anode or reduced at the cathode, so we must apply the preferential discharge theory.', zh: '水溶液同時含有溶解的離子及水分子。水本身可在陽極被氧化或在陰極被還原，因此須應用優先放電理論。' } },
      { type: 'heading', text: { en: 'Order of Discharge', zh: '放電次序' } },
      { type: 'table',
        headers: [{ en: 'Cathode — cations', zh: '陰極 — 陽離子' }, { en: 'Tendency', zh: '傾向' }],
        rows: [
          [{ en: 'K⁺, Na⁺, Ca²⁺, Mg²⁺, Al³⁺', zh: 'K⁺、Na⁺、Ca²⁺、Mg²⁺、Al³⁺' }, { en: 'Very hard to reduce (water reduced instead)', zh: '很難還原（改為還原水）' }],
          [{ en: 'Zn²⁺, Fe²⁺, Pb²⁺', zh: 'Zn²⁺、Fe²⁺、Pb²⁺' }, { en: 'Moderate', zh: '中等' }],
          [{ en: 'Cu²⁺, Ag⁺', zh: 'Cu²⁺、Ag⁺' }, { en: 'Easy — deposited preferentially', zh: '容易 —— 優先析出' }],
        ] },
      { type: 'table',
        headers: [{ en: 'Anode — anions', zh: '陽極 — 陰離子' }, { en: 'Tendency', zh: '傾向' }],
        rows: [
          [{ en: 'SO₄²⁻, NO₃⁻', zh: 'SO₄²⁻、NO₃⁻' }, { en: 'Not discharged (water oxidised → O₂)', zh: '不放電（改氧化水 → O₂）' }],
          [{ en: 'OH⁻ (from water)', zh: 'OH⁻（來自水）' }, { en: 'Oxidised to O₂ when halide dilute', zh: '鹵離子稀時被氧化成 O₂' }],
          [{ en: 'Cl⁻, Br⁻, I⁻', zh: 'Cl⁻、Br⁻、I⁻' }, { en: 'Discharged when concentrated', zh: '濃時優先放電' }],
        ] },
      { type: 'heading', text: { en: 'Key Rules', zh: '重要規則' } },
      { type: 'keyPoints', items: [
        { en: 'Cathode: Cu²⁺/Ag⁺ present → metal deposits. Only reactive-metal ions → H₂ from water.', zh: '陰極：有 Cu²⁺／Ag⁺ → 析出金屬。只有活潑金屬離子 → 由水生成 H₂。' },
        { en: 'Anode: concentrated Cl⁻/Br⁻/I⁻ → halogen. Otherwise → O₂ from water.', zh: '陽極：濃 Cl⁻／Br⁻／I⁻ → 鹵素。否則 → 由水生成 O₂。' },
        { en: 'Concentration matters: dilute Cl⁻ → O₂; concentrated Cl⁻ → Cl₂.', zh: '濃度重要：稀 Cl⁻ → O₂；濃 Cl⁻ → Cl₂。' },
      ] },
      { type: 'heading', text: { en: 'Example: CuSO₄(aq) with Inert Electrodes', zh: '例：以惰性電極電解 CuSO₄(aq)' } },
      { type: 'equation', label: { en: 'Cathode:', zh: '陰極：' }, text: 'Cu²⁺(aq) + 2e⁻ → Cu(s)' },
      { type: 'equation', label: { en: 'Anode:', zh: '陽極：' }, text: '2H₂O(l) → O₂(g) + 4H⁺(aq) + 4e⁻' },
      { type: 'info', text: { en: 'Reddish-brown copper deposits at the cathode; O₂ bubbles at the anode; the blue colour fades and the solution becomes acidic.', zh: '陰極沉積紅棕色銅；陽極放出 O₂ 氣泡；藍色變淡，溶液變酸性。' } },
      { type: 'heading', text: { en: 'Example: Dilute H₂SO₄(aq)', zh: '例：稀 H₂SO₄(aq)' } },
      { type: 'equation', label: { en: 'Cathode:', zh: '陰極：' }, text: '2H⁺(aq) + 2e⁻ → H₂(g)' },
      { type: 'equation', label: { en: 'Anode:', zh: '陽極：' }, text: '2H₂O(l) → O₂(g) + 4H⁺(aq) + 4e⁻' },
      { type: 'info', text: { en: 'H₂ : O₂ = 2 : 1 by volume. Effectively this is the electrolysis of water; the H₂SO₄ becomes more concentrated.', zh: 'H₂：O₂ 體積比 = 2：1。實際上是電解水；H₂SO₄ 濃度上升。' } },
      { type: 'heading', text: { en: 'Example: Concentrated Brine (NaCl aq)', zh: '例：濃鹽水 (NaCl aq)' } },
      { type: 'equation', label: { en: 'Cathode:', zh: '陰極：' }, text: '2H₂O(l) + 2e⁻ → H₂(g) + 2OH⁻(aq)' },
      { type: 'equation', label: { en: 'Anode:', zh: '陽極：' }, text: '2Cl⁻(aq) → Cl₂(g) + 2e⁻' },
      { type: 'info', text: { en: 'H₂ at the cathode, Cl₂ at the anode, NaOH left in solution — the chlor-alkali process. Dilute NaCl gives O₂ instead of Cl₂.', zh: '陰極 H₂、陽極 Cl₂，NaOH 留在溶液中 —— 即氯鹼法。稀 NaCl 則放出 O₂ 而非 Cl₂。' } },
    ],
    quiz: [
      { id: 'q1', type: 'mcq',
        question: { en: 'Aqueous CuSO₄ is electrolysed with platinum electrodes. What forms at the cathode?', zh: '以鉑電極電解 CuSO₄(aq)，陰極生成甚麼？' },
        options: { A: { en: 'Copper', zh: '銅' }, B: { en: 'Hydrogen', zh: '氫' }, C: { en: 'Oxygen', zh: '氧' }, D: { en: 'Sulfur dioxide', zh: '二氧化硫' } },
        answer: 'A',
        explanation: { en: 'Cu²⁺ is discharged in preference to H⁺: Cu²⁺ + 2e⁻ → Cu.', zh: 'Cu²⁺ 較 H⁺ 優先放電：Cu²⁺ + 2e⁻ → Cu。' } },
      { id: 'q2', type: 'mcq',
        question: { en: 'Concentrated brine is electrolysed. What forms at the anode?', zh: '電解濃鹽水，陽極生成甚麼？' },
        options: { A: { en: 'Oxygen', zh: '氧' }, B: { en: 'Chlorine', zh: '氯' }, C: { en: 'Hydrogen', zh: '氫' }, D: { en: 'Sodium', zh: '鈉' } },
        answer: 'B',
        explanation: { en: 'In concentrated NaCl, Cl⁻ is discharged in preference to OH⁻/water: 2Cl⁻ → Cl₂ + 2e⁻.', zh: '濃 NaCl 中 Cl⁻ 較 OH⁻／水優先放電：2Cl⁻ → Cl₂ + 2e⁻。' } },
      { id: 'q3', type: 'mcq',
        question: { en: 'In the electrolysis of dilute sulfuric acid, which gas forms at the cathode?', zh: '電解稀硫酸時陰極生成哪種氣體？' },
        options: { A: { en: 'Oxygen', zh: '氧' }, B: { en: 'Sulfur dioxide', zh: '二氧化硫' }, C: { en: 'Hydrogen', zh: '氫' }, D: { en: 'Sulfur trioxide', zh: '三氧化硫' } },
        answer: 'C',
        explanation: { en: 'At the cathode 2H⁺ + 2e⁻ → H₂. SO₄²⁻ is not discharged there.', zh: '陰極 2H⁺ + 2e⁻ → H₂。SO₄²⁻ 不在此放電。' } },
      { id: 'q4', type: 'structured',
        question: { en: '(a) Write the anode half-equation for electrolysis of CuSO₄(aq) with inert electrodes. (b) State what is observed at the cathode.', zh: '(a) 寫出以惰性電極電解 CuSO₄(aq) 時陽極的半反應方程式。(b) 說明陰極的觀察。' },
        hints: [{ en: 'Anions: SO₄²⁻ and OH⁻ — which is oxidised?', zh: '陰離子：SO₄²⁻ 和 OH⁻ —— 哪個被氧化？' }, { en: 'What forms at the cathode?', zh: '陰極生成甚麼？' }],
        answer: { en: '(a) 2H₂O(l) → O₂(g) + 4H⁺(aq) + 4e⁻ [1]\n(b) A reddish-brown solid (copper) deposits on the cathode [1]', zh: '(a) 2H₂O(l) → O₂(g) + 4H⁺(aq) + 4e⁻（1 分）\n(b) 陰極沉積紅棕色固體（銅）（1 分）' } },
      { id: 'q5', type: 'mcq',
        question: { en: 'Electrolysis of DILUTE NaCl solution most likely gives which gas at the anode?', zh: '電解稀 NaCl 溶液時，陽極最可能生成哪種氣體？' },
        options: { A: { en: 'Chlorine', zh: '氯' }, B: { en: 'Hydrogen', zh: '氫' }, C: { en: 'Oxygen', zh: '氧' }, D: { en: 'Sodium', zh: '鈉' } },
        answer: 'C',
        explanation: { en: 'With dilute Cl⁻, water is oxidised preferentially: 2H₂O → O₂ + 4H⁺ + 4e⁻.', zh: 'Cl⁻ 稀時水優先被氧化：2H₂O → O₂ + 4H⁺ + 4e⁻。' } },
      { id: 'q6', type: 'structured',
        question: { en: 'Explain why the blue colour of CuSO₄(aq) fades during electrolysis with inert electrodes.', zh: '解釋為何以惰性電極電解 CuSO₄(aq) 時藍色會變淡。' },
        hints: [{ en: 'Blue comes from Cu²⁺.', zh: '藍色來自 Cu²⁺。' }, { en: 'What happens to Cu²⁺ at the cathode?', zh: 'Cu²⁺ 在陰極發生甚麼？' }],
        answer: { en: 'The blue colour is due to Cu²⁺. At the cathode Cu²⁺ is reduced to Cu and deposited, lowering [Cu²⁺]; the solution becomes paler and eventually colourless. (2 marks)', zh: '藍色源自 Cu²⁺。陰極把 Cu²⁺ 還原成 Cu 並沉積，[Cu²⁺] 下降；溶液顏色變淡，最終無色。（2 分）' } },
    ],
  },

  {
    id: 'factors',
    title: { en: 'Factors Affecting Ion Discharge', zh: '影響離子放電的因素' },
    icon: '⚖️',
    time: '30 min',
    topic: { en: 'Factors Affecting Ion Discharge', zh: '影響離子放電的因素' },
    content: [
      { type: 'heading', text: { en: 'Three Main Factors', zh: '三個主要因素' } },
      { type: 'keyPoints', items: [
        { en: '1. Position in the electrochemical series (reduction potential).', zh: '1. 在電化學序中的位置（還原電位）。' },
        { en: '2. Concentration of the ions in solution.', zh: '2. 溶液中離子的濃度。' },
        { en: '3. Nature of the electrode (active vs inert).', zh: '3. 電極性質（活性或惰性）。' },
      ] },
      { type: 'heading', text: { en: '1. Electrochemical Series', zh: '1. 電化學序' } },
      { type: 'text', text: { en: 'For cations, a higher (more positive) reduction potential means easier reduction and preferential discharge. For anions, ease of oxidation at the anode: I⁻ > Br⁻ > Cl⁻ > OH⁻ > SO₄²⁻.', zh: '對陽離子而言，還原電位越高（越正）越易還原，越優先放電。對陰離子而言，在陽極被氧化的難易：I⁻ > Br⁻ > Cl⁻ > OH⁻ > SO₄²⁻。' } },
      { type: 'warn', text: { en: 'Order of cathode discharge: Cu²⁺ before H⁺, H⁺ before Zn²⁺, Zn²⁺ before Na⁺.', zh: '陰極放電次序：Cu²⁺ 先於 H⁺，H⁺ 先於 Zn²⁺，Zn²⁺ 先於 Na⁺。' } },
      { type: 'heading', text: { en: '2. Concentration Effect', zh: '2. 濃度效應' } },
      { type: 'keyPoints', items: [
        { en: 'Concentrated Cl⁻: Cl₂ at the anode.', zh: '濃 Cl⁻：陽極放出 Cl₂。' },
        { en: 'Dilute Cl⁻: O₂ at the anode.', zh: '稀 Cl⁻：陽極放出 O₂。' },
        { en: 'This is why industrial brine electrolysis uses concentrated NaCl.', zh: '這就是工業電解鹽水採用濃 NaCl 的原因。' },
      ] },
      { type: 'heading', text: { en: '3. Nature of Electrode', zh: '3. 電極性質' } },
      { type: 'text', text: { en: 'Inert electrodes (carbon, platinum) do not react — only solution ions are discharged. With an active electrode, the anode metal itself dissolves instead of an anion being oxidised.', zh: '惰性電極（碳、鉑）不參與反應 —— 只有溶液中的離子放電。若用活性電極，陽極金屬本身溶解，而非氧化陰離子。' } },
      { type: 'equation', label: { en: 'Active Cu anode:', zh: '活性銅陽極：' }, text: 'Cu(s) → Cu²⁺(aq) + 2e⁻' },
      { type: 'info', text: { en: 'With active copper electrodes in CuSO₄(aq) the Cu²⁺ concentration stays constant — the basis of copper refining.', zh: '在 CuSO₄(aq) 中使用活性銅電極時，Cu²⁺ 濃度保持不變 —— 此為銅精煉的基礎。' } },
      { type: 'heading', text: { en: 'Copper Refining', zh: '銅的精煉' } },
      { type: 'text', text: { en: 'Impure copper is the anode and dissolves; pure copper deposits on the cathode. More reactive impurities (Zn, Fe) dissolve but are not deposited; less reactive ones (Ag, Au) fall as anode slime.', zh: '不純的銅作陽極並溶解；純銅沉積於陰極。較活潑的雜質（Zn、Fe）溶解但不沉積；較不活潑的（Ag、Au）以陽極泥形式沉落。' } },
    ],
    quiz: [
      { id: 'q1', type: 'mcq',
        question: { en: 'A solution contains both Cu²⁺ and Zn²⁺. Which is discharged preferentially at the cathode?', zh: '溶液同時含 Cu²⁺ 和 Zn²⁺。陰極優先放電哪一種？' },
        options: { A: { en: 'Zn²⁺', zh: 'Zn²⁺' }, B: { en: 'Cu²⁺', zh: 'Cu²⁺' }, C: { en: 'Both equally', zh: '兩者相同' }, D: { en: 'Neither — H₂ forms', zh: '皆非 —— 生成 H₂' } },
        answer: 'B',
        explanation: { en: 'Cu²⁺ (E° = +0.34 V) is more easily reduced than Zn²⁺ (E° = −0.76 V), so Cu deposits.', zh: 'Cu²⁺（E° = +0.34 V）較 Zn²⁺（E° = −0.76 V）易還原，故析出 Cu。' } },
      { id: 'q2', type: 'mcq',
        question: { en: 'Concentrated NaCl gives Cl₂ at the anode but dilute NaCl gives O₂. This is explained by:', zh: '濃 NaCl 陽極放 Cl₂ 而稀 NaCl 放 O₂，原因是：' },
        options: { A: { en: 'Nature of the electrode', zh: '電極性質' }, B: { en: 'Position of Cl⁻ in the series', zh: 'Cl⁻ 在序中的位置' }, C: { en: 'Concentration of Cl⁻ vs OH⁻', zh: 'Cl⁻ 與 OH⁻ 的濃度比較' }, D: { en: 'Temperature', zh: '溫度' } },
        answer: 'C',
        explanation: { en: 'High [Cl⁻] favours Cl⁻ discharge; when dilute, water/OH⁻ is oxidised to O₂ instead.', zh: '高 [Cl⁻] 有利 Cl⁻ 放電；稀時改為氧化水／OH⁻ 生成 O₂。' } },
      { id: 'q3', type: 'structured',
        question: { en: 'CuSO₄ is electrolysed using (i) platinum and (ii) copper electrodes. State and explain the difference in the anode reaction.', zh: '分別以 (i) 鉑及 (ii) 銅電極電解 CuSO₄。指出並解釋陽極反應的分別。' },
        hints: [{ en: 'What makes an electrode "active"?', zh: '甚麼令電極成為「活性」？' }, { en: 'What happens to a dissolvable anode?', zh: '可溶解的陽極會怎樣？' }],
        answer: { en: '(i) Pt (inert): water oxidised, 2H₂O → O₂ + 4H⁺ + 4e⁻.\n(ii) Cu (active): the anode dissolves, Cu → Cu²⁺ + 2e⁻ (easier than oxidising water). (2 marks)', zh: '(i) 鉑（惰性）：氧化水，2H₂O → O₂ + 4H⁺ + 4e⁻。\n(ii) 銅（活性）：陽極溶解，Cu → Cu²⁺ + 2e⁻（較氧化水容易）。（2 分）' } },
      { id: 'q4', type: 'mcq',
        question: { en: 'In the electrolytic purification of copper, which statement is correct?', zh: '在銅的電解精煉中，哪項正確？' },
        options: { A: { en: 'Impure copper is the cathode', zh: '不純銅作陰極' }, B: { en: 'Pure copper deposits at the anode', zh: '純銅在陽極沉積' }, C: { en: 'The CuSO₄ concentration stays roughly constant', zh: 'CuSO₄ 濃度大致不變' }, D: { en: 'Au and Ag dissolve at the anode', zh: 'Au 和 Ag 在陽極溶解' } },
        answer: 'C',
        explanation: { en: 'The anode dissolves as fast as copper deposits, so [Cu²⁺] is roughly constant. Au/Ag do not dissolve (anode slime).', zh: '陽極溶解速率與陰極沉積速率相若，故 [Cu²⁺] 大致不變。Au／Ag 不溶解（成陽極泥）。' } },
    ],
  },

  {
    id: 'quantitative',
    title: { en: "Faraday's Laws of Electrolysis", zh: '法拉第電解定律' },
    icon: '📐',
    time: '30 min',
    topic: { en: "Faraday's Laws of Electrolysis", zh: '法拉第電解定律' },
    content: [
      { type: 'heading', text: { en: "Faraday's Laws", zh: '法拉第定律' } },
      { type: 'keyPoints', items: [
        { en: 'First Law: mass deposited/liberated is proportional to the quantity of charge passed.', zh: '第一定律：沉積／釋出的質量與通過的電荷量成正比。' },
        { en: 'Second Law: for a fixed charge, mass ∝ molar mass ÷ electrons in the half-equation (M/z).', zh: '第二定律：電荷固定時，質量 ∝ 摩爾質量 ÷ 半反應中的電子數（M/z）。' },
      ] },
      { type: 'heading', text: { en: 'Key Formulae', zh: '重要公式' } },
      { type: 'equation', label: { en: 'Faraday constant:', zh: '法拉第常數：' }, text: 'F = 96 500 C mol⁻¹' },
      { type: 'equation', label: { en: 'Charge:', zh: '電荷：' }, text: 'Q = I × t   (C = A × s)' },
      { type: 'equation', label: { en: 'Moles of electrons:', zh: '電子摩爾數：' }, text: 'n(e⁻) = Q / F' },
      { type: 'equation', label: { en: 'Moles of substance:', zh: '物質摩爾數：' }, text: 'n = n(e⁻) / z' },
      { type: 'equation', label: { en: 'Mass:', zh: '質量：' }, text: 'm = n × M' },
      { type: 'heading', text: { en: 'Worked Example 1', zh: '例題一' } },
      { type: 'text', text: { en: 'A current of 2.0 A is passed through CuSO₄(aq) for 30 minutes with inert electrodes. Find the mass of copper deposited. (M(Cu) = 63.5, F = 96 500)', zh: '以惰性電極通 2.0 A 電流電解 CuSO₄(aq) 30 分鐘。求沉積的銅質量。（M(Cu) = 63.5，F = 96 500）' } },
      { type: 'keyPoints', items: [
        { en: 'Q = 2.0 × 1800 = 3600 C', zh: 'Q = 2.0 × 1800 = 3600 C' },
        { en: 'n(e⁻) = 3600 / 96 500 = 0.0373 mol', zh: 'n(e⁻) = 3600 / 96 500 = 0.0373 mol' },
        { en: 'Cu²⁺ + 2e⁻ → Cu, so z = 2, n(Cu) = 0.01865 mol', zh: 'Cu²⁺ + 2e⁻ → Cu，故 z = 2，n(Cu) = 0.01865 mol' },
        { en: 'm(Cu) = 0.01865 × 63.5 = 1.19 g', zh: 'm(Cu) = 0.01865 × 63.5 = 1.19 g' },
      ] },
      { type: 'heading', text: { en: 'Worked Example 2', zh: '例題二' } },
      { type: 'text', text: { en: 'What volume of H₂ (24 L mol⁻¹ at r.t.p.) forms at the cathode when 1.5 A flows through dilute H₂SO₄ for 20 minutes?', zh: '以 1.5 A 電流電解稀 H₂SO₄ 20 分鐘，陰極生成多少體積 H₂（室溫室壓 24 L mol⁻¹）？' } },
      { type: 'keyPoints', items: [
        { en: 'Q = 1.5 × 1200 = 1800 C', zh: 'Q = 1.5 × 1200 = 1800 C' },
        { en: 'n(e⁻) = 0.01865 mol; 2H⁺ + 2e⁻ → H₂, z = 2', zh: 'n(e⁻) = 0.01865 mol；2H⁺ + 2e⁻ → H₂，z = 2' },
        { en: 'n(H₂) = 0.009326 mol → V = 0.009326 × 24 = 0.224 L', zh: 'n(H₂) = 0.009326 mol → V = 0.009326 × 24 = 0.224 L' },
      ] },
      { type: 'warn', text: { en: 'Always convert time to seconds before using Q = It.', zh: '使用 Q = It 前務必把時間換算為秒。' } },
    ],
    quiz: [
      { id: 'q1', type: 'mcq',
        question: { en: 'A current of 3.0 A is passed through molten PbBr₂ for 10 minutes. How many moles of electrons pass? (F = 96 500)', zh: '以 3.0 A 電流電解熔融 PbBr₂ 10 分鐘，通過多少摩爾電子？（F = 96 500）' },
        options: { A: { en: '0.019 mol', zh: '0.019 mol' }, B: { en: '0.093 mol', zh: '0.093 mol' }, C: { en: '0.186 mol', zh: '0.186 mol' }, D: { en: '1.86 mol', zh: '1.86 mol' } },
        answer: 'A',
        explanation: { en: 'Q = 3.0 × 600 = 1800 C; n(e⁻) = 1800 / 96 500 = 0.019 mol.', zh: 'Q = 3.0 × 600 = 1800 C；n(e⁻) = 1800 / 96 500 = 0.019 mol。' } },
      { id: 'q2', type: 'structured',
        question: { en: 'Find the mass of silver deposited when 0.50 A flows through AgNO₃(aq) for 40 minutes. (Ar(Ag) = 108, F = 96 500)', zh: '以 0.50 A 電流電解 AgNO₃(aq) 40 分鐘，求沉積的銀質量。（Ar(Ag) = 108，F = 96 500）' },
        hints: [{ en: 'Ag⁺ + e⁻ → Ag, so z = 1.', zh: 'Ag⁺ + e⁻ → Ag，故 z = 1。' }, { en: 'Use seconds for t.', zh: 't 用秒計。' }],
        answer: { en: 'Q = 0.50 × 2400 = 1200 C; n(e⁻) = 0.01244 mol; z = 1 → n(Ag) = 0.01244 mol; m = 0.01244 × 108 = 1.34 g. (3 marks)', zh: 'Q = 0.50 × 2400 = 1200 C；n(e⁻) = 0.01244 mol；z = 1 → n(Ag) = 0.01244 mol；m = 0.01244 × 108 = 1.34 g。（3 分）' } },
      { id: 'q3', type: 'mcq',
        question: { en: 'In Faraday\'s Second Law, the quantity M/z is called the:', zh: '在法拉第第二定律中，M/z 稱為：' },
        options: { A: { en: 'Molar mass', zh: '摩爾質量' }, B: { en: 'Equivalent mass', zh: '當量' }, C: { en: 'Atomic number', zh: '原子序' }, D: { en: 'Avogadro constant', zh: '阿佛加德羅常數' } },
        answer: 'B',
        explanation: { en: 'M/z is the equivalent mass — equal charges deposit equal equivalents of any substance.', zh: 'M/z 為當量 —— 相同電荷沉積相同當量的任何物質。' } },
      { id: 'q4', type: 'structured',
        question: { en: 'The same charge passes through CuSO₄(aq) and AgNO₃(aq). If 1.27 g of Cu is deposited, find the mass of Ag. (Ar: Cu = 63.5, Ag = 108)', zh: '相同電荷通過 CuSO₄(aq) 及 AgNO₃(aq)。若沉積 1.27 g Cu，求 Ag 的質量。（Ar：Cu = 63.5，Ag = 108）' },
        hints: [{ en: 'Find n(Cu) → n(e⁻) → n(Ag).', zh: '求 n(Cu) → n(e⁻) → n(Ag)。' }],
        answer: { en: 'n(Cu) = 1.27/63.5 = 0.02 mol → n(e⁻) = 0.04 mol → n(Ag) = 0.04 mol → m(Ag) = 0.04 × 108 = 4.32 g. (3 marks)', zh: 'n(Cu) = 1.27/63.5 = 0.02 mol → n(e⁻) = 0.04 mol → n(Ag) = 0.04 mol → m(Ag) = 0.04 × 108 = 4.32 g。（3 分）' } },
    ],
  },

  {
    id: 'applications',
    title: { en: 'Industrial Applications', zh: '工業應用' },
    icon: '🏭',
    time: '25 min',
    topic: { en: 'Industrial Applications of Electrolysis', zh: '電解的工業應用' },
    content: [
      { type: 'heading', text: { en: 'Electroplating', zh: '電鍍' } },
      { type: 'text', text: { en: 'Electroplating deposits a thin metal layer on an object for protection or decoration. The object is the cathode; the plating metal is the anode; the electrolyte contains ions of the plating metal.', zh: '電鍍在物件上鍍上一層薄金屬，用作保護或裝飾。物件為陰極；鍍層金屬為陽極；電解質含鍍層金屬的離子。' } },
      { type: 'keyPoints', items: [
        { en: 'Object to be plated → cathode (−).', zh: '被鍍物件 → 陰極（−）。' },
        { en: 'Plating metal → anode (+), which dissolves.', zh: '鍍層金屬 → 陽極（+），會溶解。' },
        { en: 'Electrolyte → a salt of the plating metal.', zh: '電解質 → 鍍層金屬的鹽。' },
      ] },
      { type: 'heading', text: { en: 'Purification of Copper', zh: '銅的精煉' } },
      { type: 'keyPoints', items: [
        { en: 'Impure copper: anode; pure copper: cathode; electrolyte: CuSO₄(aq).', zh: '不純銅：陽極；純銅：陰極；電解質：CuSO₄(aq)。' },
        { en: 'Reactive impurities (Fe, Zn, Ni) dissolve but are not deposited.', zh: '活潑雜質（Fe、Zn、Ni）溶解但不沉積。' },
        { en: 'Noble metals (Ag, Au) fall as anode slime.', zh: '貴金屬（Ag、Au）沉落成陽極泥。' },
      ] },
      { type: 'heading', text: { en: 'Extraction of Aluminium (Hall–Héroult)', zh: '鋁的提取（霍爾—埃魯法）' } },
      { type: 'text', text: { en: 'Al₂O₃ (m.p. ~2072 °C) is dissolved in molten cryolite (Na₃AlF₆) to lower the operating temperature to ~970 °C.', zh: 'Al₂O₃（熔點約 2072 °C）溶於熔融冰晶石 (Na₃AlF₆)，把操作溫度降至約 970 °C。' } },
      { type: 'equation', label: { en: 'Cathode:', zh: '陰極：' }, text: 'Al³⁺(l) + 3e⁻ → Al(l)' },
      { type: 'equation', label: { en: 'Anode (carbon):', zh: '陽極（碳）：' }, text: '2O²⁻(l) → O₂(g) + 4e⁻' },
      { type: 'warn', text: { en: 'The carbon anodes burn away (C + O₂ → CO₂) and must be replaced — a major cost.', zh: '碳陽極會燒蝕（C + O₂ → CO₂）須定期更換 —— 是主要成本。' } },
      { type: 'heading', text: { en: 'Chlor-Alkali Process', zh: '氯鹼法' } },
      { type: 'keyPoints', items: [
        { en: 'Anode: 2Cl⁻ → Cl₂ + 2e⁻ (chlorine for PVC, bleach).', zh: '陽極：2Cl⁻ → Cl₂ + 2e⁻（氯用於 PVC、漂白劑）。' },
        { en: 'Cathode: 2H₂O + 2e⁻ → H₂ + 2OH⁻ (hydrogen + NaOH).', zh: '陰極：2H₂O + 2e⁻ → H₂ + 2OH⁻（氫及 NaOH）。' },
        { en: 'A membrane keeps Cl₂ and NaOH apart.', zh: '隔膜使 Cl₂ 與 NaOH 分開。' },
      ] },
    ],
    quiz: [
      { id: 'q1', type: 'mcq',
        question: { en: 'To electroplate a spoon with silver, the spoon is connected as:', zh: '要在匙羹上電鍍銀，匙羹應接駁為：' },
        options: { A: { en: 'Anode, in AgNO₃', zh: '陽極，於 AgNO₃ 中' }, B: { en: 'Cathode, in AgNO₃', zh: '陰極，於 AgNO₃ 中' }, C: { en: 'Anode, in CuSO₄', zh: '陽極，於 CuSO₄ 中' }, D: { en: 'Cathode, in CuSO₄', zh: '陰極，於 CuSO₄ 中' } },
        answer: 'B',
        explanation: { en: 'The object is the cathode: Ag⁺ + e⁻ → Ag. The silver anode dissolves; electrolyte is AgNO₃.', zh: '物件作陰極：Ag⁺ + e⁻ → Ag。銀陽極溶解；電解質為 AgNO₃。' } },
      { id: 'q2', type: 'mcq',
        question: { en: 'In copper purification, why are Au and Ag not deposited at the cathode?', zh: '在銅精煉中，為何 Au 和 Ag 不在陰極沉積？' },
        options: { A: { en: 'They dissolve with the copper', zh: '它們隨銅溶解' }, B: { en: 'Removed by a membrane', zh: '被隔膜移除' }, C: { en: 'They do not dissolve from the anode', zh: '它們不從陽極溶解' }, D: { en: 'They have lower reduction potential than Cu', zh: '其還原電位低於 Cu' } },
        answer: 'C',
        explanation: { en: 'Being less reactive than copper, Au/Ag are not oxidised; they fall as anode slime.', zh: 'Au／Ag 較銅不活潑，不被氧化；以陽極泥形式沉落。' } },
      { id: 'q3', type: 'structured',
        question: { en: 'Why is Al₂O₃ dissolved in cryolite rather than electrolysed pure and molten?', zh: '為何把 Al₂O₃ 溶於冰晶石，而不直接電解純熔融態？' },
        hints: [{ en: 'Consider the energy cost of melting.', zh: '考慮熔化的能量成本。' }, { en: 'What does cryolite do to the m.p.?', zh: '冰晶石對熔點有何影響？' }],
        answer: { en: 'Pure Al₂O₃ melts at ~2072 °C, needing huge energy. Dissolving it in molten cryolite lowers the temperature to ~970 °C, making the process economical. (2 marks)', zh: '純 Al₂O₃ 熔點約 2072 °C，需極大能量。溶於熔融冰晶石可把溫度降至約 970 °C，使過程符合經濟效益。（2 分）' } },
      { id: 'q4', type: 'mcq',
        question: { en: 'The purpose of the membrane in the chlor-alkali process is to:', zh: '氯鹼法中隔膜的作用是：' },
        options: { A: { en: 'Prevent electrons crossing', zh: '阻止電子越過' }, B: { en: 'Prevent Cl₂ and NaOH mixing', zh: '阻止 Cl₂ 與 NaOH 混合' }, C: { en: 'Increase [NaCl]', zh: '增加 [NaCl]' }, D: { en: 'Let Na⁺ and Cl⁻ mix freely', zh: '讓 Na⁺ 和 Cl⁻ 自由混合' } },
        answer: 'B',
        explanation: { en: 'Cl₂ and NaOH would react if mixed. The membrane keeps the compartments separate while letting Na⁺ pass.', zh: 'Cl₂ 與 NaOH 混合會反應。隔膜使兩室分開，同時讓 Na⁺ 通過。' } },
    ],
  },

  {
    id: 'voltaic',
    title: { en: 'Voltaic Cells', zh: '伏打電池' },
    icon: '🔋',
    time: '30 min',
    topic: { en: 'Voltaic Cells', zh: '伏打電池' },
    content: [
      { type: 'heading', text: { en: 'Voltaic Cell Principles', zh: '伏打電池原理' } },
      { type: 'text', text: { en: 'A voltaic (galvanic) cell converts chemical energy from a spontaneous redox reaction into electrical energy. No external power is needed.', zh: '伏打（原）電池把自發氧化還原反應的化學能轉換為電能。不需外接電源。' } },
      { type: 'keyPoints', items: [
        { en: 'The more reactive metal is the anode (negative) — it is oxidised and dissolves.', zh: '較活潑的金屬作陽極（負極）—— 被氧化並溶解。' },
        { en: 'The less reactive metal is the cathode (positive) — cations are reduced there.', zh: '較不活潑的金屬作陰極（正極）—— 陽離子在此被還原。' },
        { en: 'Electrons flow from anode to cathode through the external circuit.', zh: '電子經外電路由陽極流向陰極。' },
      ] },
      { type: 'warn', text: { en: 'In a voltaic cell the anode is NEGATIVE — opposite to an electrolytic cell. This often confuses students.', zh: '伏打電池的陽極為負極 —— 與電解池相反。學生常混淆。' } },
      { type: 'heading', text: { en: 'Zinc–Copper Cell', zh: '鋅—銅電池' } },
      { type: 'equation', label: { en: 'Anode (Zn, −):', zh: '陽極（Zn，−）：' }, text: 'Zn(s) → Zn²⁺(aq) + 2e⁻' },
      { type: 'equation', label: { en: 'Cathode (Cu, +):', zh: '陰極（Cu，+）：' }, text: 'Cu²⁺(aq) + 2e⁻ → Cu(s)' },
      { type: 'equation', label: { en: 'Overall:', zh: '總反應：' }, text: 'Zn(s) + Cu²⁺(aq) → Zn²⁺(aq) + Cu(s)' },
      { type: 'info', text: { en: 'EMF = E°(cathode) − E°(anode) = (+0.34) − (−0.76) = +1.10 V', zh: 'EMF = E°(陰極) − E°(陽極) = (+0.34) − (−0.76) = +1.10 V' } },
      { type: 'heading', text: { en: 'The Salt Bridge', zh: '鹽橋' } },
      { type: 'keyPoints', items: [
        { en: 'It completes the circuit by letting ions move between the half-cells without mixing the solutions.', zh: '它讓離子在兩半電池間移動而不混合溶液，從而接通電路。' },
        { en: 'Without it, charge builds up and the current stops.', zh: '沒有它，電荷會累積，電流停止。' },
        { en: 'Anions move to the anode half-cell; cations move to the cathode half-cell.', zh: '陰離子移向陽極半電池；陽離子移向陰極半電池。' },
      ] },
    ],
    quiz: [
      { id: 'q1', type: 'mcq',
        question: { en: 'In a Mg–Cu voltaic cell, which is the anode?', zh: '在 Mg–Cu 伏打電池中，哪個是陽極？' },
        options: { A: { en: 'Copper', zh: '銅' }, B: { en: 'Magnesium', zh: '鎂' }, C: { en: 'Both', zh: '兩者' }, D: { en: 'Depends on electrolyte', zh: '視乎電解質' } },
        answer: 'B',
        explanation: { en: 'Mg is more reactive, so it is oxidised at the anode: Mg → Mg²⁺ + 2e⁻.', zh: 'Mg 較活潑，在陽極被氧化：Mg → Mg²⁺ + 2e⁻。' } },
      { id: 'q2', type: 'mcq',
        question: { en: 'Electrons in the external circuit of a voltaic cell flow from:', zh: '伏打電池外電路中的電子由何處流向何處？' },
        options: { A: { en: 'Cathode to anode', zh: '陰極到陽極' }, B: { en: 'Positive terminal to cathode', zh: '正極到陰極' }, C: { en: 'Anode (−) to cathode (+)', zh: '陽極（−）到陰極（+）' }, D: { en: 'Through the electrolyte', zh: '經電解質' } },
        answer: 'C',
        explanation: { en: 'The anode is negative; electrons flow through the wire from anode to cathode.', zh: '陽極為負極；電子經導線由陽極流向陰極。' } },
      { id: 'q3', type: 'structured',
        question: { en: 'A cell uses Fe and Ag electrodes. (a) Identify anode and cathode. (b) Write each half-equation.', zh: '一電池用 Fe 和 Ag 電極。(a) 指出陽極及陰極。(b) 寫出各半反應方程式。' },
        hints: [{ en: 'Fe is more reactive than Ag.', zh: 'Fe 較 Ag 活潑。' }, { en: 'Anode = oxidation.', zh: '陽極 = 氧化。' }],
        answer: { en: '(a) Anode: Fe; Cathode: Ag.\n(b) Fe → Fe²⁺ + 2e⁻; Ag⁺ + e⁻ → Ag. (3 marks)', zh: '(a) 陽極：Fe；陰極：Ag。\n(b) Fe → Fe²⁺ + 2e⁻；Ag⁺ + e⁻ → Ag。（3 分）' } },
      { id: 'q4', type: 'mcq',
        question: { en: 'The function of the salt bridge is to:', zh: '鹽橋的作用是：' },
        options: { A: { en: 'Let electrons flow between half-cells', zh: '讓電子在半電池間流動' }, B: { en: 'Let ions migrate and maintain neutrality', zh: '讓離子遷移並維持電中性' }, C: { en: 'Prevent all ionic mixing', zh: '阻止一切離子混合' }, D: { en: 'Increase the EMF', zh: '增加電動勢' } },
        answer: 'B',
        explanation: { en: 'It lets ions (not electrons) move to keep each half-cell electrically neutral.', zh: '它讓離子（非電子）移動，使每個半電池保持電中性。' } },
    ],
  },

  {
    id: 'daniel',
    title: { en: 'The Daniel Cell & EMF', zh: '丹尼爾電池與電動勢' },
    icon: '🔌',
    time: '30 min',
    topic: { en: 'The Daniel Cell and EMF', zh: '丹尼爾電池與電動勢' },
    content: [
      { type: 'heading', text: { en: 'The Daniel Cell', zh: '丹尼爾電池' } },
      { type: 'text', text: { en: 'A classic voltaic cell: Zn in ZnSO₄(aq) and Cu in CuSO₄(aq), joined by a salt bridge.', zh: '經典伏打電池：Zn 於 ZnSO₄(aq)、Cu 於 CuSO₄(aq)，以鹽橋連接。' } },
      { type: 'equation', label: { en: 'Anode (Zn):', zh: '陽極（Zn）：' }, text: 'Zn(s) → Zn²⁺(aq) + 2e⁻' },
      { type: 'equation', label: { en: 'Cathode (Cu):', zh: '陰極（Cu）：' }, text: 'Cu²⁺(aq) + 2e⁻ → Cu(s)' },
      { type: 'equation', label: { en: 'Cell EMF:', zh: '電池電動勢：' }, text: 'E°cell = (+0.34) − (−0.76) = +1.10 V' },
      { type: 'heading', text: { en: 'Standard Electrode Potentials (E°)', zh: '標準電極電位 (E°)' } },
      { type: 'text', text: { en: 'E° values are measured relative to the standard hydrogen electrode (SHE, 0.00 V) under standard conditions.', zh: 'E° 值相對於標準氫電極（SHE，0.00 V）於標準狀況下量度。' } },
      { type: 'table',
        headers: [{ en: 'Reduction half-reaction', zh: '還原半反應' }, { en: 'E° (V)', zh: 'E° (V)' }],
        rows: [
          [{ en: 'Cl₂ + 2e⁻ → 2Cl⁻', zh: 'Cl₂ + 2e⁻ → 2Cl⁻' }, { en: '+1.36', zh: '+1.36' }],
          [{ en: 'Ag⁺ + e⁻ → Ag', zh: 'Ag⁺ + e⁻ → Ag' }, { en: '+0.80', zh: '+0.80' }],
          [{ en: 'Cu²⁺ + 2e⁻ → Cu', zh: 'Cu²⁺ + 2e⁻ → Cu' }, { en: '+0.34', zh: '+0.34' }],
          [{ en: '2H⁺ + 2e⁻ → H₂', zh: '2H⁺ + 2e⁻ → H₂' }, { en: '0.00', zh: '0.00' }],
          [{ en: 'Fe²⁺ + 2e⁻ → Fe', zh: 'Fe²⁺ + 2e⁻ → Fe' }, { en: '−0.44', zh: '−0.44' }],
          [{ en: 'Zn²⁺ + 2e⁻ → Zn', zh: 'Zn²⁺ + 2e⁻ → Zn' }, { en: '−0.76', zh: '−0.76' }],
          [{ en: 'Mg²⁺ + 2e⁻ → Mg', zh: 'Mg²⁺ + 2e⁻ → Mg' }, { en: '−2.37', zh: '−2.37' }],
        ] },
      { type: 'heading', text: { en: 'Predicting EMF & Feasibility', zh: '預測電動勢與可行性' } },
      { type: 'equation', label: { en: 'Rule:', zh: '規則：' }, text: 'E°cell = E°(cathode) − E°(anode);  E°cell > 0 → spontaneous' },
      { type: 'info', text: { en: 'The species with the more positive E° is reduced (cathode); the more negative is oxidised (anode).', zh: 'E° 較正者被還原（陰極）；較負者被氧化（陽極）。' } },
    ],
    quiz: [
      { id: 'q1', type: 'structured',
        question: { en: 'Calculate the EMF of a cell from Ag/Ag⁺ and Fe/Fe²⁺, state the anode, and write the overall equation. (E°: Ag⁺/Ag = +0.80, Fe²⁺/Fe = −0.44)', zh: '由 Ag/Ag⁺ 及 Fe/Fe²⁺ 組成電池，計算電動勢，指出陽極並寫出總方程式。（E°：Ag⁺/Ag = +0.80，Fe²⁺/Fe = −0.44）' },
        hints: [{ en: 'Cathode = more positive E°.', zh: '陰極 = E° 較正。' }],
        answer: { en: 'Cathode: Ag; Anode: Fe. E°cell = 0.80 − (−0.44) = +1.24 V. Overall: Fe + 2Ag⁺ → Fe²⁺ + 2Ag. (3 marks)', zh: '陰極：Ag；陽極：Fe。E°cell = 0.80 − (−0.44) = +1.24 V。總反應：Fe + 2Ag⁺ → Fe²⁺ + 2Ag。（3 分）' } },
      { id: 'q2', type: 'mcq',
        question: { en: 'Which pair gives the greatest EMF?', zh: '哪一對給出最大電動勢？' },
        options: { A: { en: 'Cu/Ag', zh: 'Cu/Ag' }, B: { en: 'Zn/Cu', zh: 'Zn/Cu' }, C: { en: 'Mg/Cu', zh: 'Mg/Cu' }, D: { en: 'Fe/Ni', zh: 'Fe/Ni' } },
        answer: 'C',
        explanation: { en: 'E° = (+0.34) − (−2.37) = +2.71 V, the largest difference.', zh: 'E° = (+0.34) − (−2.37) = +2.71 V，差值最大。' } },
      { id: 'q3', type: 'mcq',
        question: { en: 'A cell has E°cell = −0.50 V. This means:', zh: '某電池 E°cell = −0.50 V，意即：' },
        options: { A: { en: 'The reaction is spontaneous', zh: '反應自發' }, B: { en: 'Non-spontaneous under standard conditions', zh: '標準狀況下非自發' }, C: { en: 'No current can ever flow', zh: '永不能有電流' }, D: { en: 'It produces 0.50 V', zh: '產生 0.50 V' } },
        answer: 'B',
        explanation: { en: 'A negative E°cell means the reaction as written is non-spontaneous; energy must be supplied.', zh: '負的 E°cell 表示所寫反應非自發；須供給能量。' } },
      { id: 'q4', type: 'mcq',
        question: { en: 'A standard Daniel cell (no current flowing) has EMF of:', zh: '標準丹尼爾電池（無電流）電動勢為：' },
        options: { A: { en: '> 1.10 V', zh: '> 1.10 V' }, B: { en: 'Exactly 1.10 V', zh: '正好 1.10 V' }, C: { en: 'Zero', zh: '零' }, D: { en: 'Negative', zh: '負值' } },
        answer: 'B',
        explanation: { en: 'At standard conditions the Daniel cell EMF is +1.10 V.', zh: '在標準狀況下，丹尼爾電池電動勢為 +1.10 V。' } },
    ],
  },

  {
    id: 'fuel',
    title: { en: 'Fuel Cells', zh: '燃料電池' },
    icon: '🌿',
    time: '20 min',
    topic: { en: 'Fuel Cells', zh: '燃料電池' },
    content: [
      { type: 'heading', text: { en: 'Hydrogen–Oxygen Fuel Cell', zh: '氫氧燃料電池' } },
      { type: 'text', text: { en: 'A fuel cell converts chemical energy of a fuel (H₂) and oxidant (O₂) directly into electricity. Overall: 2H₂ + O₂ → 2H₂O. It produces electricity continuously as long as fuel is supplied.', zh: '燃料電池把燃料（H₂）和氧化劑（O₂）的化學能直接轉為電能。總反應：2H₂ + O₂ → 2H₂O。只要持續供應燃料便可連續發電。' } },
      { type: 'heading', text: { en: 'Alkaline (KOH)', zh: '鹼性 (KOH)' } },
      { type: 'equation', label: { en: 'Anode:', zh: '陽極：' }, text: 'H₂(g) + 2OH⁻(aq) → 2H₂O(l) + 2e⁻' },
      { type: 'equation', label: { en: 'Cathode:', zh: '陰極：' }, text: 'O₂(g) + 2H₂O(l) + 4e⁻ → 4OH⁻(aq)' },
      { type: 'heading', text: { en: 'Acidic / PEM', zh: '酸性 / PEM' } },
      { type: 'equation', label: { en: 'Anode:', zh: '陽極：' }, text: 'H₂(g) → 2H⁺(aq) + 2e⁻' },
      { type: 'equation', label: { en: 'Cathode:', zh: '陰極：' }, text: 'O₂(g) + 4H⁺(aq) + 4e⁻ → 2H₂O(l)' },
      { type: 'heading', text: { en: 'Advantages & Disadvantages', zh: '優點與缺點' } },
      { type: 'table',
        headers: [{ en: 'Advantages', zh: '優點' }, { en: 'Disadvantages', zh: '缺點' }],
        rows: [
          [{ en: 'Only product is water (no CO₂)', zh: '唯一產物是水（無 CO₂）' }, { en: 'H₂ storage/distribution is difficult', zh: 'H₂ 儲存／運送困難' }],
          [{ en: 'High efficiency (~60%)', zh: '效率高（約 60%）' }, { en: 'Expensive Pt catalyst', zh: '鉑催化劑昂貴' }],
          [{ en: 'Continuous — refuel not recharge', zh: '連續運作 —— 只需補充燃料' }, { en: 'H₂ often made from fossil fuels', zh: 'H₂ 多由化石燃料製造' }],
          [{ en: 'Silent, no moving parts (PEM)', zh: '安靜、無活動部件（PEM）' }, { en: 'H₂ is flammable', zh: 'H₂ 易燃' }],
        ] },
    ],
    quiz: [
      { id: 'q1', type: 'mcq',
        question: { en: 'In an alkaline H₂–O₂ fuel cell, what is produced at the cathode?', zh: '在鹼性氫氧燃料電池中，陰極產生甚麼？' },
        options: { A: { en: 'Hydrogen', zh: '氫' }, B: { en: 'Oxygen', zh: '氧' }, C: { en: 'Hydroxide ions', zh: '氫氧根離子' }, D: { en: 'Water', zh: '水' } },
        answer: 'C',
        explanation: { en: 'At the cathode: O₂ + 2H₂O + 4e⁻ → 4OH⁻.', zh: '陰極：O₂ + 2H₂O + 4e⁻ → 4OH⁻。' } },
      { id: 'q2', type: 'mcq',
        question: { en: 'A major advantage of hydrogen fuel cells over petrol engines is:', zh: '氫燃料電池相對汽油引擎的主要優點是：' },
        options: { A: { en: 'Lower cost', zh: '成本較低' }, B: { en: 'More energy per gram of fuel', zh: '每克燃料能量更多' }, C: { en: 'Only exhaust is water', zh: '排放物只有水' }, D: { en: 'Hydrogen is widely available', zh: '氫很容易取得' } },
        answer: 'C',
        explanation: { en: 'The only exhaust is water vapour — zero emission at point of use.', zh: '唯一排放為水蒸氣 —— 使用時零排放。' } },
      { id: 'q3', type: 'structured',
        question: { en: 'Write the half-equation for oxidation of hydrogen at the anode in an ACIDIC fuel cell.', zh: '寫出酸性燃料電池中陽極氫氧化的半反應方程式。' },
        hints: [{ en: 'Oxidation = losing electrons.', zh: '氧化 = 失去電子。' }],
        answer: { en: 'H₂(g) → 2H⁺(aq) + 2e⁻ [1 mark — state symbols needed]', zh: 'H₂(g) → 2H⁺(aq) + 2e⁻（1 分 —— 須寫狀態符號）' } },
      { id: 'q4', type: 'mcq',
        question: { en: 'Unlike a conventional battery, a fuel cell:', zh: '與傳統電池不同，燃料電池：' },
        options: { A: { en: 'Needs no electrolyte', zh: '不需電解質' }, B: { en: 'Runs continuously while fuel is supplied', zh: '只要供應燃料便可連續運作' }, C: { en: 'Has higher self-discharge', zh: '自放電較高' }, D: { en: 'Produces AC', zh: '產生交流電' } },
        answer: 'B',
        explanation: { en: 'A fuel cell does not store energy internally; it runs as long as H₂ and O₂ are supplied.', zh: '燃料電池不在內部儲能；只要供應 H₂ 和 O₂ 便持續運作。' } },
    ],
  },
]
